<?php

namespace Database\Seeders;

use Illuminate\Database\Seeder;
use Illuminate\Support\Facades\DB;

class OptionSeeder extends Seeder
{
    /**
     * Run the database seeds.
     *
     * @return void
     */
    public function run()
    {
        DB::unprepared("
        INSERT INTO `option_questions` VALUES(NULL,1, 1, 0, NULL, NULL, NULL);
INSERT INTO `option_questions` VALUES(NULL,1, 2, 1, NULL, NULL, NULL);
INSERT INTO `option_questions` VALUES(NULL,2, 1, 1, NULL, NULL, NULL);
INSERT INTO `option_questions` VALUES(NULL,2, 2, 0, NULL, NULL, NULL);
INSERT INTO `option_questions` VALUES(NULL,3, 1, 0, NULL, NULL, NULL);
INSERT INTO `option_questions` VALUES(NULL,3, 2, 1, NULL, NULL, NULL);
INSERT INTO `option_questions` VALUES(NULL,4, 1, 1, NULL, NULL, NULL);
INSERT INTO `option_questions` VALUES(NULL,4, 2, 0, NULL, NULL, NULL);
INSERT INTO `option_questions` VALUES(NULL,5, 1, 1, NULL, NULL, NULL);
INSERT INTO `option_questions` VALUES(NULL,5, 2, 0, NULL, NULL, NULL);
INSERT INTO `option_questions` VALUES(NULL,6, 1, 1, NULL, NULL, NULL);
INSERT INTO `option_questions` VALUES(NULL,6, 2, 0, NULL, NULL, NULL);
INSERT INTO `option_questions` VALUES(NULL,7, 1, 1, NULL, NULL, NULL);
INSERT INTO `option_questions` VALUES(NULL,7, 2, 0, NULL, NULL, NULL);
INSERT INTO `option_questions` VALUES(NULL,8, 1, 1, NULL, NULL, NULL);
INSERT INTO `option_questions` VALUES(NULL,8, 2, 0, NULL, NULL, NULL);
INSERT INTO `option_questions` VALUES(NULL,9, 1, 1, NULL, NULL, NULL);
INSERT INTO `option_questions` VALUES(NULL,9, 2, 0, NULL, NULL, NULL);
INSERT INTO `option_questions` VALUES(NULL,10, 1, 1, NULL, NULL, NULL);
INSERT INTO `option_questions` VALUES(NULL,10, 2, 0, NULL, NULL, NULL);
INSERT INTO `option_questions` VALUES(NULL,11, 1, 0, NULL, NULL, NULL);
INSERT INTO `option_questions` VALUES(NULL,11, 2, 1, NULL, NULL, NULL);
INSERT INTO `option_questions` VALUES(NULL,12, 1, 1, NULL, NULL, NULL);
INSERT INTO `option_questions` VALUES(NULL,12, 2, 0, NULL, NULL, NULL);
INSERT INTO `option_questions` VALUES(NULL,13, 1, 1, NULL, NULL, NULL);
INSERT INTO `option_questions` VALUES(NULL,13, 2, 0, NULL, NULL, NULL);
INSERT INTO `option_questions` VALUES(NULL,14, 1, 0, NULL, NULL, NULL);
INSERT INTO `option_questions` VALUES(NULL,14, 2, 1, NULL, NULL, NULL);
INSERT INTO `option_questions` VALUES(NULL,15, 1, 1, NULL, NULL, NULL);
INSERT INTO `option_questions` VALUES(NULL,15, 2, 0, NULL, NULL, NULL);
INSERT INTO `option_questions` VALUES(NULL,16, 1, 1, NULL, NULL, NULL);
INSERT INTO `option_questions` VALUES(NULL,16, 2, 0, NULL, NULL, NULL);
INSERT INTO `option_questions` VALUES(NULL,17, 1, 1, NULL, NULL, NULL);
INSERT INTO `option_questions` VALUES(NULL,17, 2, 0, NULL, NULL, NULL);
INSERT INTO `option_questions` VALUES(NULL,18, 1, 0, NULL, NULL, NULL);
INSERT INTO `option_questions` VALUES(NULL,18, 2, 1, NULL, NULL, NULL);
INSERT INTO `option_questions` VALUES(NULL,19, 1, 1, NULL, NULL, NULL);
INSERT INTO `option_questions` VALUES(NULL,19, 2, 0, NULL, NULL, NULL);
INSERT INTO `option_questions` VALUES(NULL,20, 1, 1, NULL, NULL, NULL);
INSERT INTO `option_questions` VALUES(NULL,20, 2, 0, NULL, NULL, NULL);
INSERT INTO `option_questions` VALUES(NULL,21, 1, 1, NULL, NULL, NULL);
INSERT INTO `option_questions` VALUES(NULL,21, 2, 0, NULL, NULL, NULL);
INSERT INTO `option_questions` VALUES(NULL,22, 1, 1, NULL, NULL, NULL);
INSERT INTO `option_questions` VALUES(NULL,22, 2, 0, NULL, NULL, NULL);
INSERT INTO `option_questions` VALUES(NULL,23, 1, 1, NULL, NULL, NULL);
INSERT INTO `option_questions` VALUES(NULL,23, 2, 0, NULL, NULL, NULL);
INSERT INTO `option_questions` VALUES(NULL,24, 1, 1, NULL, NULL, NULL);
INSERT INTO `option_questions` VALUES(NULL,24, 2, 0, NULL, NULL, NULL);
INSERT INTO `option_questions` VALUES(NULL,25, 1, 0, NULL, NULL, NULL);
INSERT INTO `option_questions` VALUES(NULL,25, 2, 1, NULL, NULL, NULL);
INSERT INTO `option_questions` VALUES(NULL,26, 1, 1, NULL, NULL, NULL);
INSERT INTO `option_questions` VALUES(NULL,26, 2, 0, NULL, NULL, NULL);
INSERT INTO `option_questions` VALUES(NULL,27, 1, 1, NULL, NULL, NULL);
INSERT INTO `option_questions` VALUES(NULL,27, 2, 0, NULL, NULL, NULL);
INSERT INTO `option_questions` VALUES(NULL,28, 1, 1, NULL, NULL, NULL);
INSERT INTO `option_questions` VALUES(NULL,28, 2, 0, NULL, NULL, NULL);
INSERT INTO `option_questions` VALUES(NULL,29, 1, 1, NULL, NULL, NULL);
INSERT INTO `option_questions` VALUES(NULL,29, 2, 0, NULL, NULL, NULL);
INSERT INTO `option_questions` VALUES(NULL,30, 1, 1, NULL, NULL, NULL);
INSERT INTO `option_questions` VALUES(NULL,30, 2, 0, NULL, NULL, NULL);
INSERT INTO `option_questions` VALUES(NULL,31, 1, 1, NULL, NULL, NULL);
INSERT INTO `option_questions` VALUES(NULL,31, 2, 0, NULL, NULL, NULL);
INSERT INTO `option_questions` VALUES(NULL,32, 1, 1, NULL, NULL, NULL);
INSERT INTO `option_questions` VALUES(NULL,32, 2, 0, NULL, NULL, NULL);
INSERT INTO `option_questions` VALUES(NULL,33, 1, 1, NULL, NULL, NULL);
INSERT INTO `option_questions` VALUES(NULL,33, 2, 0, NULL, NULL, NULL);
INSERT INTO `option_questions` VALUES(NULL,34, 1, 1, NULL, NULL, NULL);
INSERT INTO `option_questions` VALUES(NULL,34, 2, 0, NULL, NULL, NULL);
INSERT INTO `option_questions` VALUES(NULL,35, 1, 0, NULL, NULL, NULL);
INSERT INTO `option_questions` VALUES(NULL,35, 2, 1, NULL, NULL, NULL);
INSERT INTO `option_questions` VALUES(NULL,36, 1, 1, NULL, NULL, NULL);
INSERT INTO `option_questions` VALUES(NULL,36, 2, 0, NULL, NULL, NULL);
INSERT INTO `option_questions` VALUES(NULL,37, 1, 1, NULL, NULL, NULL);
INSERT INTO `option_questions` VALUES(NULL,37, 2, 0, NULL, NULL, NULL);
INSERT INTO `option_questions` VALUES(NULL,38, 1, 0, NULL, NULL, NULL);
INSERT INTO `option_questions` VALUES(NULL,38, 2, 1, NULL, NULL, NULL);
INSERT INTO `option_questions` VALUES(NULL,39, 1, 1, NULL, NULL, NULL);
INSERT INTO `option_questions` VALUES(NULL,39, 2, 0, NULL, NULL, NULL);
INSERT INTO `option_questions` VALUES(NULL,40, 1, 1, NULL, NULL, NULL);
INSERT INTO `option_questions` VALUES(NULL,40, 2, 0, NULL, NULL, NULL);
INSERT INTO `option_questions` VALUES(NULL,41, 1, 1, NULL, NULL, NULL);
INSERT INTO `option_questions` VALUES(NULL,41, 2, 0, NULL, NULL, NULL);
INSERT INTO `option_questions` VALUES(NULL,42, 1, 1, NULL, NULL, NULL);
INSERT INTO `option_questions` VALUES(NULL,42, 2, 0, NULL, NULL, NULL);
INSERT INTO `option_questions` VALUES(NULL,43, 1, 1, NULL, NULL, NULL);
INSERT INTO `option_questions` VALUES(NULL,43, 2, 0, NULL, NULL, NULL);
INSERT INTO `option_questions` VALUES(NULL,44, 1, 1, NULL, NULL, NULL);
INSERT INTO `option_questions` VALUES(NULL,44, 2, 0, NULL, NULL, NULL);
INSERT INTO `option_questions` VALUES(NULL,45, 1, 1, NULL, NULL, NULL);
INSERT INTO `option_questions` VALUES(NULL,45, 2, 0, NULL, NULL, NULL);
INSERT INTO `option_questions` VALUES(NULL,46, 1, 1, NULL, NULL, NULL);
INSERT INTO `option_questions` VALUES(NULL,46, 2, 0, NULL, NULL, NULL);
INSERT INTO `option_questions` VALUES(NULL,47, 1, 1, NULL, NULL, NULL);
INSERT INTO `option_questions` VALUES(NULL,47, 2, 0, NULL, NULL, NULL);
INSERT INTO `option_questions` VALUES(NULL,48, 1, 1, NULL, NULL, NULL);
INSERT INTO `option_questions` VALUES(NULL,48, 2, 0, NULL, NULL, NULL);
INSERT INTO `option_questions` VALUES(NULL,49, 1, 1, NULL, NULL, NULL);
INSERT INTO `option_questions` VALUES(NULL,49, 2, 0, NULL, NULL, NULL);
INSERT INTO `option_questions` VALUES(NULL,50, 1, 1, NULL, NULL, NULL);
INSERT INTO `option_questions` VALUES(NULL,50, 2, 0, NULL, NULL, NULL);
INSERT INTO `option_questions` VALUES(NULL,51, 1, 1, NULL, NULL, NULL);
INSERT INTO `option_questions` VALUES(NULL,51, 2, 0, NULL, NULL, NULL);
INSERT INTO `option_questions` VALUES(NULL,52, 1, 1, NULL, NULL, NULL);
INSERT INTO `option_questions` VALUES(NULL,52, 2, 0, NULL, NULL, NULL);
INSERT INTO `option_questions` VALUES(NULL,53, 1, 1, NULL, NULL, NULL);
INSERT INTO `option_questions` VALUES(NULL,53, 2, 0, NULL, NULL, NULL);
INSERT INTO `option_questions` VALUES(NULL,54, 1, 1, NULL, NULL, NULL);
INSERT INTO `option_questions` VALUES(NULL,54, 2, 0, NULL, NULL, NULL);
INSERT INTO `option_questions` VALUES(NULL,55, 1, 1, NULL, NULL, NULL);
INSERT INTO `option_questions` VALUES(NULL,55, 2, 0, NULL, NULL, NULL);
INSERT INTO `option_questions` VALUES(NULL,56, 1, 1, NULL, NULL, NULL);
INSERT INTO `option_questions` VALUES(NULL,56, 2, 0, NULL, NULL, NULL);
INSERT INTO `option_questions` VALUES(NULL,57, 1, 0, NULL, NULL, NULL);
INSERT INTO `option_questions` VALUES(NULL,57, 2, 1, NULL, NULL, NULL);
INSERT INTO `option_questions` VALUES(NULL,58, 1, 1, NULL, NULL, NULL);
INSERT INTO `option_questions` VALUES(NULL,58, 2, 0, NULL, NULL, NULL);
INSERT INTO `option_questions` VALUES(NULL,59, 1, 1, NULL, NULL, NULL);
INSERT INTO `option_questions` VALUES(NULL,59, 2, 0, NULL, NULL, NULL);


INSERT INTO `option_questions` VALUES(NULL,60, 3, 0, NULL, NULL, NULL);
INSERT INTO `option_questions` VALUES(NULL,60, 4, 1, NULL, NULL, NULL);
INSERT INTO `option_questions` VALUES(NULL,60, 5, 2, NULL, NULL, NULL);
INSERT INTO `option_questions` VALUES(NULL,60, 6, 3, NULL, NULL, NULL);
INSERT INTO `option_questions` VALUES(NULL,60, 7, 4, NULL, NULL, NULL);
INSERT INTO `option_questions` VALUES(NULL,60, 8, 5, NULL, NULL, NULL);
INSERT INTO `option_questions` VALUES(NULL,61, 3, 0, NULL, NULL, NULL);
INSERT INTO `option_questions` VALUES(NULL,61, 4, 1, NULL, NULL, NULL);
INSERT INTO `option_questions` VALUES(NULL,61, 5, 2, NULL, NULL, NULL);
INSERT INTO `option_questions` VALUES(NULL,61, 6, 3, NULL, NULL, NULL);
INSERT INTO `option_questions` VALUES(NULL,61, 7, 4, NULL, NULL, NULL);
INSERT INTO `option_questions` VALUES(NULL,61, 8, 5, NULL, NULL, NULL);
INSERT INTO `option_questions` VALUES(NULL,62, 3, 0, NULL, NULL, NULL);
INSERT INTO `option_questions` VALUES(NULL,62, 4, 1, NULL, NULL, NULL);
INSERT INTO `option_questions` VALUES(NULL,62, 5, 2, NULL, NULL, NULL);
INSERT INTO `option_questions` VALUES(NULL,62, 6, 3, NULL, NULL, NULL);
INSERT INTO `option_questions` VALUES(NULL,62, 7, 4, NULL, NULL, NULL);
INSERT INTO `option_questions` VALUES(NULL,62, 8, 5, NULL, NULL, NULL);
INSERT INTO `option_questions` VALUES(NULL,63, 3, 0, NULL, NULL, NULL);
INSERT INTO `option_questions` VALUES(NULL,63, 4, 1, NULL, NULL, NULL);
INSERT INTO `option_questions` VALUES(NULL,63, 5, 2, NULL, NULL, NULL);
INSERT INTO `option_questions` VALUES(NULL,63, 6, 3, NULL, NULL, NULL);
INSERT INTO `option_questions` VALUES(NULL,63, 7, 4, NULL, NULL, NULL);
INSERT INTO `option_questions` VALUES(NULL,63, 8, 5, NULL, NULL, NULL);
INSERT INTO `option_questions` VALUES(NULL,64, 3, 0, NULL, NULL, NULL);
INSERT INTO `option_questions` VALUES(NULL,64, 4, 1, NULL, NULL, NULL);
INSERT INTO `option_questions` VALUES(NULL,64, 5, 2, NULL, NULL, NULL);
INSERT INTO `option_questions` VALUES(NULL,64, 6, 3, NULL, NULL, NULL);
INSERT INTO `option_questions` VALUES(NULL,64, 7, 4, NULL, NULL, NULL);
INSERT INTO `option_questions` VALUES(NULL,64, 8, 5, NULL, NULL, NULL);
INSERT INTO `option_questions` VALUES(NULL,65, 3, 0, NULL, NULL, NULL);
INSERT INTO `option_questions` VALUES(NULL,65, 4, 1, NULL, NULL, NULL);
INSERT INTO `option_questions` VALUES(NULL,65, 5, 2, NULL, NULL, NULL);
INSERT INTO `option_questions` VALUES(NULL,65, 6, 3, NULL, NULL, NULL);
INSERT INTO `option_questions` VALUES(NULL,65, 7, 4, NULL, NULL, NULL);
INSERT INTO `option_questions` VALUES(NULL,65, 8, 5, NULL, NULL, NULL);
INSERT INTO `option_questions` VALUES(NULL,66, 3, 0, NULL, NULL, NULL);
INSERT INTO `option_questions` VALUES(NULL,66, 4, 1, NULL, NULL, NULL);
INSERT INTO `option_questions` VALUES(NULL,66, 5, 2, NULL, NULL, NULL);
INSERT INTO `option_questions` VALUES(NULL,66, 6, 3, NULL, NULL, NULL);
INSERT INTO `option_questions` VALUES(NULL,66, 7, 4, NULL, NULL, NULL);
INSERT INTO `option_questions` VALUES(NULL,66, 8, 5, NULL, NULL, NULL);

INSERT INTO `option_questions` VALUES(NULL,67, 9, 0, NULL, NULL, NULL);
INSERT INTO `option_questions` VALUES(NULL,67, 10, 1, NULL, NULL, NULL);
INSERT INTO `option_questions` VALUES(NULL,67, 11, 2, NULL, NULL, NULL);
INSERT INTO `option_questions` VALUES(NULL,67, 12, 3, NULL, NULL, NULL);

INSERT INTO `option_questions` VALUES(NULL,68, 9, 0, NULL, NULL, NULL);
INSERT INTO `option_questions` VALUES(NULL,68, 10, 1, NULL, NULL, NULL);
INSERT INTO `option_questions` VALUES(NULL,68, 11, 2, NULL, NULL, NULL);
INSERT INTO `option_questions` VALUES(NULL,68, 12, 3, NULL, NULL, NULL);
INSERT INTO `option_questions` VALUES(NULL,69, 9, 0, NULL, NULL, NULL);
INSERT INTO `option_questions` VALUES(NULL,69, 10, 1, NULL, NULL, NULL);
INSERT INTO `option_questions` VALUES(NULL,69, 11, 2, NULL, NULL, NULL);
INSERT INTO `option_questions` VALUES(NULL,69, 12, 3, NULL, NULL, NULL);
INSERT INTO `option_questions` VALUES(NULL,70, 9, 0, NULL, NULL, NULL);
INSERT INTO `option_questions` VALUES(NULL,70, 10, 1, NULL, NULL, NULL);
INSERT INTO `option_questions` VALUES(NULL,70, 11, 2, NULL, NULL, NULL);
INSERT INTO `option_questions` VALUES(NULL,70, 12, 3, NULL, NULL, NULL);
INSERT INTO `option_questions` VALUES(NULL,71, 9, 0, NULL, NULL, NULL);
INSERT INTO `option_questions` VALUES(NULL,71, 10, 1, NULL, NULL, NULL);
INSERT INTO `option_questions` VALUES(NULL,71, 11, 2, NULL, NULL, NULL);
INSERT INTO `option_questions` VALUES(NULL,71, 12, 3, NULL, NULL, NULL);
INSERT INTO `option_questions` VALUES(NULL,72, 9, 0, NULL, NULL, NULL);
INSERT INTO `option_questions` VALUES(NULL,72, 10, 1, NULL, NULL, NULL);
INSERT INTO `option_questions` VALUES(NULL,72, 11, 2, NULL, NULL, NULL);
INSERT INTO `option_questions` VALUES(NULL,72, 12, 3, NULL, NULL, NULL);
INSERT INTO `option_questions` VALUES(NULL,73, 9, 0, NULL, NULL, NULL);
INSERT INTO `option_questions` VALUES(NULL,73, 10, 1, NULL, NULL, NULL);
INSERT INTO `option_questions` VALUES(NULL,73, 11, 2, NULL, NULL, NULL);
INSERT INTO `option_questions` VALUES(NULL,73, 12, 3, NULL, NULL, NULL);
INSERT INTO `option_questions` VALUES(NULL,74, 9, 0, NULL, NULL, NULL);
INSERT INTO `option_questions` VALUES(NULL,74, 10, 1, NULL, NULL, NULL);
INSERT INTO `option_questions` VALUES(NULL,74, 11, 2, NULL, NULL, NULL);
INSERT INTO `option_questions` VALUES(NULL,74, 12, 3, NULL, NULL, NULL);
INSERT INTO `option_questions` VALUES(NULL,75, 9, 0, NULL, NULL, NULL);
INSERT INTO `option_questions` VALUES(NULL,75, 10, 1, NULL, NULL, NULL);
INSERT INTO `option_questions` VALUES(NULL,75, 11, 2, NULL, NULL, NULL);
INSERT INTO `option_questions` VALUES(NULL,75, 12, 3, NULL, NULL, NULL);
INSERT INTO `option_questions` VALUES(NULL,76, 9, 0, NULL, NULL, NULL);
INSERT INTO `option_questions` VALUES(NULL,76, 10, 1, NULL, NULL, NULL);
INSERT INTO `option_questions` VALUES(NULL,76, 11, 2, NULL, NULL, NULL);
INSERT INTO `option_questions` VALUES(NULL,76, 12, 3, NULL, NULL, NULL);
INSERT INTO `option_questions` VALUES(NULL,77, 9, 0, NULL, NULL, NULL);
INSERT INTO `option_questions` VALUES(NULL,77, 10, 1, NULL, NULL, NULL);
INSERT INTO `option_questions` VALUES(NULL,77, 11, 2, NULL, NULL, NULL);
INSERT INTO `option_questions` VALUES(NULL,77, 12, 3, NULL, NULL, NULL);
INSERT INTO `option_questions` VALUES(NULL,78, 9, 0, NULL, NULL, NULL);
INSERT INTO `option_questions` VALUES(NULL,78, 10, 1, NULL, NULL, NULL);
INSERT INTO `option_questions` VALUES(NULL,78, 11, 2, NULL, NULL, NULL);
INSERT INTO `option_questions` VALUES(NULL,78, 12, 3, NULL, NULL, NULL);
INSERT INTO `option_questions` VALUES(NULL,79, 9, 0, NULL, NULL, NULL);
INSERT INTO `option_questions` VALUES(NULL,79, 10, 1, NULL, NULL, NULL);
INSERT INTO `option_questions` VALUES(NULL,79, 11, 2, NULL, NULL, NULL);
INSERT INTO `option_questions` VALUES(NULL,79, 12, 3, NULL, NULL, NULL);
INSERT INTO `option_questions` VALUES(NULL,80, 9, 0, NULL, NULL, NULL);
INSERT INTO `option_questions` VALUES(NULL,80, 10, 1, NULL, NULL, NULL);
INSERT INTO `option_questions` VALUES(NULL,80, 11, 2, NULL, NULL, NULL);
INSERT INTO `option_questions` VALUES(NULL,80, 12, 3, NULL, NULL, NULL);
INSERT INTO `option_questions` VALUES(NULL,81, 9, 0, NULL, NULL, NULL);
INSERT INTO `option_questions` VALUES(NULL,81, 10, 1, NULL, NULL, NULL);
INSERT INTO `option_questions` VALUES(NULL,81, 11, 2, NULL, NULL, NULL);
INSERT INTO `option_questions` VALUES(NULL,81, 12, 3, NULL, NULL, NULL);
INSERT INTO `option_questions` VALUES(NULL,82, 9, 0, NULL, NULL, NULL);
INSERT INTO `option_questions` VALUES(NULL,82, 10, 1, NULL, NULL, NULL);
INSERT INTO `option_questions` VALUES(NULL,82, 11, 2, NULL, NULL, NULL);
INSERT INTO `option_questions` VALUES(NULL,82, 12, 3, NULL, NULL, NULL);
INSERT INTO `option_questions` VALUES(NULL,83, 9, 0, NULL, NULL, NULL);
INSERT INTO `option_questions` VALUES(NULL,83, 10, 1, NULL, NULL, NULL);
INSERT INTO `option_questions` VALUES(NULL,83, 11, 2, NULL, NULL, NULL);
INSERT INTO `option_questions` VALUES(NULL,83, 12, 3, NULL, NULL, NULL);
INSERT INTO `option_questions` VALUES(NULL,84, 9, 0, NULL, NULL, NULL);
INSERT INTO `option_questions` VALUES(NULL,84, 10, 1, NULL, NULL, NULL);
INSERT INTO `option_questions` VALUES(NULL,84, 11, 2, NULL, NULL, NULL);
INSERT INTO `option_questions` VALUES(NULL,84, 12, 3, NULL, NULL, NULL);
INSERT INTO `option_questions` VALUES(NULL,85, 9, 0, NULL, NULL, NULL);
INSERT INTO `option_questions` VALUES(NULL,85, 10, 1, NULL, NULL, NULL);
INSERT INTO `option_questions` VALUES(NULL,85, 11, 2, NULL, NULL, NULL);
INSERT INTO `option_questions` VALUES(NULL,85, 12, 3, NULL, NULL, NULL);
INSERT INTO `option_questions` VALUES(NULL,86, 9, 0, NULL, NULL, NULL);
INSERT INTO `option_questions` VALUES(NULL,86, 10, 1, NULL, NULL, NULL);
INSERT INTO `option_questions` VALUES(NULL,86, 11, 2, NULL, NULL, NULL);
INSERT INTO `option_questions` VALUES(NULL,86, 12, 3, NULL, NULL, NULL);
INSERT INTO `option_questions` VALUES(NULL,87, 9, 0, NULL, NULL, NULL);
INSERT INTO `option_questions` VALUES(NULL,87, 10, 1, NULL, NULL, NULL);
INSERT INTO `option_questions` VALUES(NULL,87, 11, 2, NULL, NULL, NULL);
INSERT INTO `option_questions` VALUES(NULL,87, 12, 3, NULL, NULL, NULL);

INSERT INTO `option_questions` VALUES(NULL,88, 13, 4, NULL, NULL, NULL);
INSERT INTO `option_questions` VALUES(NULL,88, 14, 3, NULL, NULL, NULL);
INSERT INTO `option_questions` VALUES(NULL,88, 15, 2, NULL, NULL, NULL);
INSERT INTO `option_questions` VALUES(NULL,88, 16, 1, NULL, NULL, NULL);
INSERT INTO `option_questions` VALUES(NULL,89, 13, 1, NULL, NULL, NULL);
INSERT INTO `option_questions` VALUES(NULL,89, 14, 2, NULL, NULL, NULL);
INSERT INTO `option_questions` VALUES(NULL,89, 15, 3, NULL, NULL, NULL);
INSERT INTO `option_questions` VALUES(NULL,89, 16, 4, NULL, NULL, NULL);
INSERT INTO `option_questions` VALUES(NULL,90, 13, 4, NULL, NULL, NULL);
INSERT INTO `option_questions` VALUES(NULL,90, 14, 3, NULL, NULL, NULL);
INSERT INTO `option_questions` VALUES(NULL,90, 15, 2, NULL, NULL, NULL);
INSERT INTO `option_questions` VALUES(NULL,90, 16, 1, NULL, NULL, NULL);
INSERT INTO `option_questions` VALUES(NULL,91, 13, 4, NULL, NULL, NULL);
INSERT INTO `option_questions` VALUES(NULL,91, 14, 3, NULL, NULL, NULL);
INSERT INTO `option_questions` VALUES(NULL,91, 15, 2, NULL, NULL, NULL);
INSERT INTO `option_questions` VALUES(NULL,91, 16, 1, NULL, NULL, NULL);
INSERT INTO `option_questions` VALUES(NULL,92, 13, 1, NULL, NULL, NULL);
INSERT INTO `option_questions` VALUES(NULL,92, 14, 2, NULL, NULL, NULL);
INSERT INTO `option_questions` VALUES(NULL,92, 15, 3, NULL, NULL, NULL);
INSERT INTO `option_questions` VALUES(NULL,92, 16, 4, NULL, NULL, NULL);
INSERT INTO `option_questions` VALUES(NULL,93, 13, 1, NULL, NULL, NULL);
INSERT INTO `option_questions` VALUES(NULL,93, 14, 2, NULL, NULL, NULL);
INSERT INTO `option_questions` VALUES(NULL,93, 15, 3, NULL, NULL, NULL);
INSERT INTO `option_questions` VALUES(NULL,93, 16, 4, NULL, NULL, NULL);
INSERT INTO `option_questions` VALUES(NULL,94, 13, 4, NULL, NULL, NULL);
INSERT INTO `option_questions` VALUES(NULL,94, 14, 3, NULL, NULL, NULL);
INSERT INTO `option_questions` VALUES(NULL,94, 15, 2, NULL, NULL, NULL);
INSERT INTO `option_questions` VALUES(NULL,94, 16, 1, NULL, NULL, NULL);
INSERT INTO `option_questions` VALUES(NULL,95, 13, 1, NULL, NULL, NULL);
INSERT INTO `option_questions` VALUES(NULL,95, 14, 2, NULL, NULL, NULL);
INSERT INTO `option_questions` VALUES(NULL,95, 15, 3, NULL, NULL, NULL);
INSERT INTO `option_questions` VALUES(NULL,95, 16, 4, NULL, NULL, NULL);
INSERT INTO `option_questions` VALUES(NULL,96, 13, 1, NULL, NULL, NULL);
INSERT INTO `option_questions` VALUES(NULL,96, 14, 2, NULL, NULL, NULL);
INSERT INTO `option_questions` VALUES(NULL,96, 15, 3, NULL, NULL, NULL);
INSERT INTO `option_questions` VALUES(NULL,96, 16, 4, NULL, NULL, NULL);
INSERT INTO `option_questions` VALUES(NULL,97, 13, 4, NULL, NULL, NULL);
INSERT INTO `option_questions` VALUES(NULL,97, 14, 3, NULL, NULL, NULL);
INSERT INTO `option_questions` VALUES(NULL,97, 15, 2, NULL, NULL, NULL);
INSERT INTO `option_questions` VALUES(NULL,97, 16, 1, NULL, NULL, NULL);

INSERT INTO `option_questions` VALUES(NULL,98, 17, 1, NULL, NULL, NULL);
INSERT INTO `option_questions` VALUES(NULL,98, 18, 2, NULL, NULL, NULL);
INSERT INTO `option_questions` VALUES(NULL,98, 19, 3, NULL, NULL, NULL);
INSERT INTO `option_questions` VALUES(NULL,98, 20, 4, NULL, NULL, NULL);
INSERT INTO `option_questions` VALUES(NULL,99, 17, 1, NULL, NULL, NULL);
INSERT INTO `option_questions` VALUES(NULL,99, 18, 2, NULL, NULL, NULL);
INSERT INTO `option_questions` VALUES(NULL,99, 19, 3, NULL, NULL, NULL);
INSERT INTO `option_questions` VALUES(NULL,99, 20, 4, NULL, NULL, NULL);

INSERT INTO `option_questions` VALUES(NULL,100, 17, 1, NULL, NULL, NULL);
INSERT INTO `option_questions` VALUES(NULL,100, 18, 2, NULL, NULL, NULL);
INSERT INTO `option_questions` VALUES(NULL,100, 19, 3, NULL, NULL, NULL);
INSERT INTO `option_questions` VALUES(NULL,100, 20, 4, NULL, NULL, NULL);

INSERT INTO `option_questions` VALUES(NULL,101, 17, 1, NULL, NULL, NULL);
INSERT INTO `option_questions` VALUES(NULL,101, 18, 2, NULL, NULL, NULL);
INSERT INTO `option_questions` VALUES(NULL,101, 19, 3, NULL, NULL, NULL);
INSERT INTO `option_questions` VALUES(NULL,101, 20, 4, NULL, NULL, NULL);
INSERT INTO `option_questions` VALUES(NULL,102, 17, 1, NULL, NULL, NULL);
INSERT INTO `option_questions` VALUES(NULL,102, 18, 2, NULL, NULL, NULL);
INSERT INTO `option_questions` VALUES(NULL,102, 19, 3, NULL, NULL, NULL);
INSERT INTO `option_questions` VALUES(NULL,102, 20, 4, NULL, NULL, NULL);
INSERT INTO `option_questions` VALUES(NULL,103, 17, 1, NULL, NULL, NULL);
INSERT INTO `option_questions` VALUES(NULL,103, 18, 2, NULL, NULL, NULL);
INSERT INTO `option_questions` VALUES(NULL,103, 19, 3, NULL, NULL, NULL);
INSERT INTO `option_questions` VALUES(NULL,103, 20, 4, NULL, NULL, NULL);

INSERT INTO `option_questions` VALUES(NULL,104, 17, 1, NULL, NULL, NULL);
INSERT INTO `option_questions` VALUES(NULL,104, 18, 2, NULL, NULL, NULL);
INSERT INTO `option_questions` VALUES(NULL,104, 19, 3, NULL, NULL, NULL);
INSERT INTO `option_questions` VALUES(NULL,104, 20, 4, NULL, NULL, NULL);
INSERT INTO `option_questions` VALUES(NULL,105, 17, 1, NULL, NULL, NULL);
INSERT INTO `option_questions` VALUES(NULL,105, 18, 2, NULL, NULL, NULL);
INSERT INTO `option_questions` VALUES(NULL,105, 19, 3, NULL, NULL, NULL);
INSERT INTO `option_questions` VALUES(NULL,105, 20, 4, NULL, NULL, NULL);
INSERT INTO `option_questions` VALUES(NULL,106, 17, 1, NULL, NULL, NULL);
INSERT INTO `option_questions` VALUES(NULL,106, 18, 2, NULL, NULL, NULL);
INSERT INTO `option_questions` VALUES(NULL,106, 19, 3, NULL, NULL, NULL);
INSERT INTO `option_questions` VALUES(NULL,106, 20, 4, NULL, NULL, NULL);

INSERT INTO `option_questions` VALUES(NULL,107, 17, 1, NULL, NULL, NULL);
INSERT INTO `option_questions` VALUES(NULL,107, 18, 2, NULL, NULL, NULL);
INSERT INTO `option_questions` VALUES(NULL,107, 19, 3, NULL, NULL, NULL);
INSERT INTO `option_questions` VALUES(NULL,107, 20, 4, NULL, NULL, NULL);

INSERT INTO `option_questions` VALUES(NULL,108, 17, 1, NULL, NULL, NULL);
INSERT INTO `option_questions` VALUES(NULL,108, 18, 2, NULL, NULL, NULL);
INSERT INTO `option_questions` VALUES(NULL,108, 19, 3, NULL, NULL, NULL);
INSERT INTO `option_questions` VALUES(NULL,108, 20, 4, NULL, NULL, NULL);

INSERT INTO `option_questions` VALUES(NULL,109, 17, 1, NULL, NULL, NULL);
INSERT INTO `option_questions` VALUES(NULL,109, 18, 2, NULL, NULL, NULL);
INSERT INTO `option_questions` VALUES(NULL,109, 19, 3, NULL, NULL, NULL);
INSERT INTO `option_questions` VALUES(NULL,109, 20, 4, NULL, NULL, NULL);

INSERT INTO `option_questions` VALUES(NULL,110, 17, 1, NULL, NULL, NULL);
INSERT INTO `option_questions` VALUES(NULL,110, 4, 2, NULL, NULL, NULL);
INSERT INTO `option_questions` VALUES(NULL,110, 38, 3, NULL, NULL, NULL);
INSERT INTO `option_questions` VALUES(NULL,110, 7, 4, NULL, NULL, NULL);
INSERT INTO `option_questions` VALUES(NULL,110, 21, 5, NULL, NULL, NULL);

INSERT INTO `option_questions` VALUES(NULL,111, 17, 1, NULL, NULL, NULL);
INSERT INTO `option_questions` VALUES(NULL,111, 4, 2, NULL, NULL, NULL);
INSERT INTO `option_questions` VALUES(NULL,111, 38, 3, NULL, NULL, NULL);
INSERT INTO `option_questions` VALUES(NULL,111, 7, 4, NULL, NULL, NULL);
INSERT INTO `option_questions` VALUES(NULL,111, 21, 5, NULL, NULL, NULL);
INSERT INTO `option_questions` VALUES(NULL,112, 17, 1, NULL, NULL, NULL);
INSERT INTO `option_questions` VALUES(NULL,112, 4, 2, NULL, NULL, NULL);
INSERT INTO `option_questions` VALUES(NULL,112, 38, 3, NULL, NULL, NULL);
INSERT INTO `option_questions` VALUES(NULL,112, 7, 4, NULL, NULL, NULL);
INSERT INTO `option_questions` VALUES(NULL,112, 21, 5, NULL, NULL, NULL);

INSERT INTO `option_questions` VALUES(NULL,113, 17, 1, NULL, NULL, NULL);
INSERT INTO `option_questions` VALUES(NULL,113, 4, 2, NULL, NULL, NULL);
INSERT INTO `option_questions` VALUES(NULL,113, 38, 3, NULL, NULL, NULL);
INSERT INTO `option_questions` VALUES(NULL,113, 7, 4, NULL, NULL, NULL);
INSERT INTO `option_questions` VALUES(NULL,113, 21, 5, NULL, NULL, NULL);

INSERT INTO `option_questions` VALUES(NULL,114, 17, 1, NULL, NULL, NULL);
INSERT INTO `option_questions` VALUES(NULL,114, 4, 2, NULL, NULL, NULL);
INSERT INTO `option_questions` VALUES(NULL,114, 38, 3, NULL, NULL, NULL);
INSERT INTO `option_questions` VALUES(NULL,114, 7, 4, NULL, NULL, NULL);
INSERT INTO `option_questions` VALUES(NULL,114, 21, 5, NULL, NULL, NULL);

INSERT INTO `option_questions` VALUES(NULL,115, 17, 5, NULL, NULL, NULL);
INSERT INTO `option_questions` VALUES(NULL,115, 4, 4, NULL, NULL, NULL);
INSERT INTO `option_questions` VALUES(NULL,115, 38, 3, NULL, NULL, NULL);
INSERT INTO `option_questions` VALUES(NULL,115, 7, 2, NULL, NULL, NULL);
INSERT INTO `option_questions` VALUES(NULL,115, 21, 1, NULL, NULL, NULL);

INSERT INTO `option_questions` VALUES(NULL,116, 17, 1, NULL, NULL, NULL);
INSERT INTO `option_questions` VALUES(NULL,116, 4, 2, NULL, NULL, NULL);
INSERT INTO `option_questions` VALUES(NULL,116, 38, 3, NULL, NULL, NULL);
INSERT INTO `option_questions` VALUES(NULL,116, 7, 4, NULL, NULL, NULL);
INSERT INTO `option_questions` VALUES(NULL,116, 21, 5, NULL, NULL, NULL);

INSERT INTO `option_questions` VALUES(NULL,117, 16, 5, NULL, NULL, NULL);
INSERT INTO `option_questions` VALUES(NULL,117, 15, 4, NULL, NULL, NULL);
INSERT INTO `option_questions` VALUES(NULL,117, 22, 3, NULL, NULL, NULL);
INSERT INTO `option_questions` VALUES(NULL,117, 14, 2, NULL, NULL, NULL);
INSERT INTO `option_questions` VALUES(NULL,117, 13, 1, NULL, NULL, NULL);

INSERT INTO `option_questions` VALUES(NULL,118, 16, 1, NULL, NULL, NULL);
INSERT INTO `option_questions` VALUES(NULL,118, 15, 2, NULL, NULL, NULL);
INSERT INTO `option_questions` VALUES(NULL,118, 22, 3, NULL, NULL, NULL);
INSERT INTO `option_questions` VALUES(NULL,118, 14, 4, NULL, NULL, NULL);
INSERT INTO `option_questions` VALUES(NULL,118, 13, 5, NULL, NULL, NULL);

INSERT INTO `option_questions` VALUES(NULL,119, 16, 5, NULL, NULL, NULL);
INSERT INTO `option_questions` VALUES(NULL,119, 15, 4, NULL, NULL, NULL);
INSERT INTO `option_questions` VALUES(NULL,119, 22, 3, NULL, NULL, NULL);
INSERT INTO `option_questions` VALUES(NULL,119, 14, 2, NULL, NULL, NULL);
INSERT INTO `option_questions` VALUES(NULL,119, 13, 1, NULL, NULL, NULL);

INSERT INTO `option_questions` VALUES(NULL,120, 16, 1, NULL, NULL, NULL);
INSERT INTO `option_questions` VALUES(NULL,120, 15, 2, NULL, NULL, NULL);
INSERT INTO `option_questions` VALUES(NULL,120, 22, 3, NULL, NULL, NULL);
INSERT INTO `option_questions` VALUES(NULL,120, 14, 4, NULL, NULL, NULL);
INSERT INTO `option_questions` VALUES(NULL,120, 13, 5, NULL, NULL, NULL);

INSERT INTO `option_questions` VALUES(NULL,121, 16, 5, NULL, NULL, NULL);
INSERT INTO `option_questions` VALUES(NULL,121, 15, 4, NULL, NULL, NULL);
INSERT INTO `option_questions` VALUES(NULL,121, 22, 3, NULL, NULL, NULL);
INSERT INTO `option_questions` VALUES(NULL,121, 14, 2, NULL, NULL, NULL);
INSERT INTO `option_questions` VALUES(NULL,121, 13, 1, NULL, NULL, NULL);

INSERT INTO `option_questions` VALUES(NULL,122, 16, 1, NULL, NULL, NULL);
INSERT INTO `option_questions` VALUES(NULL,122, 15, 2, NULL, NULL, NULL);
INSERT INTO `option_questions` VALUES(NULL,122, 22, 3, NULL, NULL, NULL);
INSERT INTO `option_questions` VALUES(NULL,122, 14, 4, NULL, NULL, NULL);
INSERT INTO `option_questions` VALUES(NULL,122, 13, 5, NULL, NULL, NULL);

INSERT INTO `option_questions` VALUES(NULL,123, 16, 1, NULL, NULL, NULL);
INSERT INTO `option_questions` VALUES(NULL,123, 15, 2, NULL, NULL, NULL);
INSERT INTO `option_questions` VALUES(NULL,123, 22, 3, NULL, NULL, NULL);
INSERT INTO `option_questions` VALUES(NULL,123, 14, 4, NULL, NULL, NULL);
INSERT INTO `option_questions` VALUES(NULL,123, 13, 5, NULL, NULL, NULL);
INSERT INTO `option_questions` VALUES(NULL,124, 16, 1, NULL, NULL, NULL);
INSERT INTO `option_questions` VALUES(NULL,124, 15, 2, NULL, NULL, NULL);
INSERT INTO `option_questions` VALUES(NULL,124, 22, 3, NULL, NULL, NULL);
INSERT INTO `option_questions` VALUES(NULL,124, 14, 4, NULL, NULL, NULL);
INSERT INTO `option_questions` VALUES(NULL,124, 13, 5, NULL, NULL, NULL);
INSERT INTO `option_questions` VALUES(NULL,125, 16, 1, NULL, NULL, NULL);
INSERT INTO `option_questions` VALUES(NULL,125, 15, 2, NULL, NULL, NULL);
INSERT INTO `option_questions` VALUES(NULL,125, 22, 3, NULL, NULL, NULL);
INSERT INTO `option_questions` VALUES(NULL,125, 14, 4, NULL, NULL, NULL);
INSERT INTO `option_questions` VALUES(NULL,125, 13, 5, NULL, NULL, NULL);
INSERT INTO `option_questions` VALUES(NULL,126, 16, 1, NULL, NULL, NULL);
INSERT INTO `option_questions` VALUES(NULL,126, 15, 2, NULL, NULL, NULL);
INSERT INTO `option_questions` VALUES(NULL,126, 22, 3, NULL, NULL, NULL);
INSERT INTO `option_questions` VALUES(NULL,126, 14, 4, NULL, NULL, NULL);
INSERT INTO `option_questions` VALUES(NULL,126, 13, 5, NULL, NULL, NULL);
INSERT INTO `option_questions` VALUES(NULL,127, 16, 1, NULL, NULL, NULL);
INSERT INTO `option_questions` VALUES(NULL,127, 15, 2, NULL, NULL, NULL);
INSERT INTO `option_questions` VALUES(NULL,127, 22, 3, NULL, NULL, NULL);
INSERT INTO `option_questions` VALUES(NULL,127, 14, 4, NULL, NULL, NULL);
INSERT INTO `option_questions` VALUES(NULL,127, 13, 5, NULL, NULL, NULL);
INSERT INTO `option_questions` VALUES(NULL,128, 16, 1, NULL, NULL, NULL);
INSERT INTO `option_questions` VALUES(NULL,128, 15, 2, NULL, NULL, NULL);
INSERT INTO `option_questions` VALUES(NULL,128, 22, 3, NULL, NULL, NULL);
INSERT INTO `option_questions` VALUES(NULL,128, 14, 4, NULL, NULL, NULL);
INSERT INTO `option_questions` VALUES(NULL,128, 13, 5, NULL, NULL, NULL);
INSERT INTO `option_questions` VALUES(NULL,129, 16, 1, NULL, NULL, NULL);
INSERT INTO `option_questions` VALUES(NULL,129, 15, 2, NULL, NULL, NULL);
INSERT INTO `option_questions` VALUES(NULL,129, 22, 3, NULL, NULL, NULL);
INSERT INTO `option_questions` VALUES(NULL,129, 14, 4, NULL, NULL, NULL);
INSERT INTO `option_questions` VALUES(NULL,129, 13, 5, NULL, NULL, NULL);
INSERT INTO `option_questions` VALUES(NULL,130, 16, 1, NULL, NULL, NULL);
INSERT INTO `option_questions` VALUES(NULL,130, 15, 2, NULL, NULL, NULL);
INSERT INTO `option_questions` VALUES(NULL,130, 22, 3, NULL, NULL, NULL);
INSERT INTO `option_questions` VALUES(NULL,130, 14, 4, NULL, NULL, NULL);
INSERT INTO `option_questions` VALUES(NULL,130, 13, 5, NULL, NULL, NULL);
INSERT INTO `option_questions` VALUES(NULL,131, 16, 1, NULL, NULL, NULL);
INSERT INTO `option_questions` VALUES(NULL,131, 15, 2, NULL, NULL, NULL);
INSERT INTO `option_questions` VALUES(NULL,131, 22, 3, NULL, NULL, NULL);
INSERT INTO `option_questions` VALUES(NULL,131, 14, 4, NULL, NULL, NULL);
INSERT INTO `option_questions` VALUES(NULL,131, 13, 5, NULL, NULL, NULL);

INSERT INTO `option_questions` VALUES(NULL,132, 32, 1, NULL, NULL, NULL);
INSERT INTO `option_questions` VALUES(NULL,132, 33, 2, NULL, NULL, NULL);
INSERT INTO `option_questions` VALUES(NULL,132, 34, 3, NULL, NULL, NULL);

INSERT INTO `option_questions` VALUES(NULL, 133, 29, 1, NULL, NULL, NULL);
INSERT INTO `option_questions` VALUES(NULL, 133, 30, 2, NULL, NULL, NULL);
INSERT INTO `option_questions` VALUES(NULL, 133, 31, 3, NULL, NULL, NULL);
INSERT INTO `option_questions` VALUES(NULL, 134, 35, 1, NULL, NULL, NULL);
INSERT INTO `option_questions` VALUES(NULL, 134, 36, 2, NULL, NULL, NULL);
INSERT INTO `option_questions` VALUES(NULL, 134, 37, 3, NULL, NULL, NULL);
INSERT INTO `option_questions` VALUES(NULL, 135, 39, 1, NULL, NULL, NULL);
INSERT INTO `option_questions` VALUES(NULL, 135, 40, 2, NULL, NULL, NULL);
INSERT INTO `option_questions` VALUES(NULL, 135, 41, 3, NULL, NULL, NULL);
INSERT INTO `option_questions` VALUES(NULL, 136, 42, 1, NULL, NULL, NULL);
INSERT INTO `option_questions` VALUES(NULL, 136, 43, 2, NULL, NULL, NULL);
INSERT INTO `option_questions` VALUES(NULL, 136, 44, 3, NULL, NULL, NULL);
INSERT INTO `option_questions` VALUES(NULL, 137, 45, 1, NULL, NULL, NULL);
INSERT INTO `option_questions` VALUES(NULL, 137, 46, 2, NULL, NULL, NULL);
INSERT INTO `option_questions` VALUES(NULL, 137, 47, 3, NULL, NULL, NULL);
INSERT INTO `option_questions` VALUES(NULL, 138, 48, 1, NULL, NULL, NULL);
INSERT INTO `option_questions` VALUES(NULL, 138, 49, 2, NULL, NULL, NULL);
INSERT INTO `option_questions` VALUES(NULL, 138, 50, 3, NULL, NULL, NULL);
INSERT INTO `option_questions` VALUES(NULL, 139, 51, 1, NULL, NULL, NULL);
INSERT INTO `option_questions` VALUES(NULL, 139, 52, 2, NULL, NULL, NULL);
INSERT INTO `option_questions` VALUES(NULL, 139, 53, 3, NULL, NULL, NULL);
INSERT INTO `option_questions` VALUES(NULL, 140, 54, 1, NULL, NULL, NULL);
INSERT INTO `option_questions` VALUES(NULL, 140, 55, 2, NULL, NULL, NULL);
INSERT INTO `option_questions` VALUES(NULL, 140, 56, 3, NULL, NULL, NULL);
INSERT INTO `option_questions` VALUES(NULL, 141, 57, 1, NULL, NULL, NULL);
INSERT INTO `option_questions` VALUES(NULL, 141, 58, 2, NULL, NULL, NULL);
INSERT INTO `option_questions` VALUES(NULL, 141, 59, 3, NULL, NULL, NULL);
        ");
        DB::unprepared("
        INSERT INTO `report_characteristics` VALUES(1, 0.00, 7.00, 'Normal', 1, 'You seem to be a positive person who is not much affected by negative thoughts and apprehensions. The level of your concentration and attention seems to be good and hence, the tendency to make small mistakes will be low. It seems that you are peaceful and balanced most of the time and take decisions after thinking through. Your sleep quality is probably good and the propensity to get agitated or irritated seems to be insignificant. It appears that you like to plan for your future instead of worrying about your troubles. Your performance at work seems to be good and you would be satisfied with your work-life. Personal and social life seems to be wonderful and you probably are an inspiration to the people around you.\r\n', 'inverse', 1, 1, NULL, '2021-02-04 20:00:38', '2021-02-04 20:00:38');
        INSERT INTO `report_characteristics` VALUES(2, 8.00, 9.00, 'Mild', 1, 'You seem to have a positive outlook on life. Concentration and attention level appears to be satisfactory. It seems that you seldom make any mistakes. You seem to be in a state of tranquillity, without any negativity and apprehensions. Your sleep quality is probably decent and propensity to get agitated or irritated might be low. You seem to be performing well at your workplace and handling the responsibilities of your family wonderfully.\r\n\r\nOf late your worries might be troubling you. On some days you might feel a little uncomfortable due to stress at work or home. There is a likelihood that you might be a little more sensitive than usual. The tendency to make small mistakes might increase if your ability to concentrate is hindered. Your sleep quality might get affected if you’re unable to keep your worries at the bay. Your family members, friends, or colleagues might be the first ones to notice any changes in your behaviour.\r\n', 'inverse', 1, 1, NULL, '2021-02-04 20:00:39', '2021-02-04 20:00:39');
        INSERT INTO `report_characteristics` VALUES(3, 10.00, 14.00, 'Moderate', 1, 'You seem to be a calm and happy person and worries might seldom affect you. You seem to keep negativity and apprehensions out at the bay, hence, the tendency to get agitated or irritated appears be low. Propensity to plan about the future for mitigating any risks seems to be prevalent. This might keep you up on some nights. Once in a while, you might feel that your concentration and attention is getting affected due to stress at work or home. When you are engaged in work, you seem to be an efficient member of the team, however, sometimes you might lose the track and end up thinking about your future a bit too much. \r\n', 'inverse', 1, 1, NULL, '2021-02-04 20:00:39', '2021-02-04 20:00:39');
        INSERT INTO `report_characteristics` VALUES(4, 15.00, 19.00, 'Severe', 1, 'Things at work or home might not be going as per your way. It could be an overwhelming feeling. You might feel uneasy and there could be a constant sense of worry. You might also experience breathlessness, rapid heartbeat, palpitations, sweating, trembling, etc. Your performance might get affected because of the burden of unreasonable worries. Your concentration and attention level could also be getting affected. You might feel on the edge and even small issues could be affecting you deeply.\r\n', 'inverse', 1, 1, NULL, '2021-02-04 20:00:39', '2021-02-04 20:00:39');
        INSERT INTO `report_characteristics` VALUES(5, 20.00, 42.00, 'Extremely Severe', 1, 'You might be feeling extremely uneasy and there could be a tendency to ignore personal and professional responsibilities. Tasks which seemed easy earlier might be getting difficult to complete. Your heartbeat and breath could be abnormal most of the times because of constant worries. Your irritation or agitation to even a trivial stimulus could be magnified. Your ability to think and understand might have gotten affected significantly. You might be having sleepless nights. Due to so many changes, there is a presumption that you might be feeling incapable of continuing work or even taking up meager responsibilities. \r\n', 'inverse', 1, 1, NULL, '2021-02-04 20:00:39', '2021-02-04 20:00:39');
        INSERT INTO `report_characteristics` VALUES(6, 0.00, 9.00, 'Normal', 2, 'You seem to have an ability to understand and balance your emotions, understand what is causing problems and manage yourself proactively and reactively. It seems that you are an emotionally strong person and do not allow ups and downs of life to impact your mental wellbeing. Your quality to keep personal, social and professional life in harmony seems to be remarkable. Your reaction to something is usually as per the intensity of the situation. You seem to like being around people and a part of a social circle. At work, you seem to be energetic and full of motivation. It seems that you are satisfied with your performance while striving to achieve more. Mood swings might not affect you often and usually, you are in a balanced state of mind', 'inverse', 1, 1, NULL, '2021-02-04 20:00:39', '2021-02-04 20:00:39');
        INSERT INTO `report_characteristics` VALUES(7, 10.00, 13.00, 'Mild', 2, 'You seem to be an energetic and easy-going person who might like to be a part of group activities and interacting with new people. It seems that you are able to understand your emotions and thoughts and dissect them to know what is causing what? You are probably capable of managing your work-life balance well. \r\nOf late, you may notice a shift in your energy levels and excitement for things that make you happy. Once in a while, you might not want to be part of social gatherings because you are not excited about it. You might experience mood swings rarely but it might affect your performance on such days. \r\n', 'inverse', 1, 1, NULL, '2021-02-04 20:00:39', '2021-02-04 20:00:39');
        INSERT INTO `report_characteristics` VALUES(8, 14.00, 20.00, 'Moderate', 2, 'You seem to be an easy-going person who likes to be a part of group activities and interacting with new people. It seems that you understand your emotions and thoughts and dissect them to know what is causing what. You probably are capable to manage your work-life balance well but sometimes, you might face problems in your personal, professional and social life. At work, you could be performing well and completing tasks but there can be times when you end up making small mistakes. Focusing on things might be getting a little difficult when you are surrounded by a lot of work or thoughts. You probably feel fatigued a little more than often and sometimes there could be some body aches too. ', 'inverse', 1, 1, NULL, '2021-02-04 20:00:39', '2021-02-04 20:00:39');
        INSERT INTO `report_characteristics` VALUES(9, 21.00, 27.00, 'Severe', 2, 'You might be unable to find happiness in the things that excited you in past. Social gatherings may not be as exciting and you might be feeling distant from your friends and family. There could be lack in energy and you might feel like resting or sleeping throughout the day. Your job might not interest you anymore. There could be increased sensitivity towards trivial matters.  Your loved ones might have talked to you about this shift in your behavior. Feeling of agitation and irritation is understandable in such a situation. You might have a perception of having seen, heard, touched, tasted or smelled something that isn’t actually present. \r\n', 'inverse', 1, 1, NULL, '2021-02-04 20:00:39', '2021-02-04 20:00:39');
        INSERT INTO `report_characteristics` VALUES(10, 28.00, 200.00, 'Extremely Severe', 2, 'You might be experiencing sadness and distress mostly throughout the day. Socializing might be a little difficult these days. Things that made you happy might be unable to give you a sense of satisfaction or contentment. You might be having troubles in continuing your routine work and personal activities. You might not be waking up fresh and excited to start the new day. There could be feelings of tiredness, lethargy, sleeplessness, etc. Sometimes, you might even experience body aches. Things might not be looking great at your workplace as well. You might not be interested in your work, hence, increasing numbers of absent days. Your difficult feelings and behaviour might be concerning to your friends or family. Feelings of agitation and irritation are natural in such a situation. You could perceive having seen, heard, touched, tasted or smelled something that isn’t present.\r\n', 'inverse', 1, 1, NULL, '2021-02-04 20:00:39', '2021-02-04 20:00:39');
        INSERT INTO `report_characteristics` VALUES(11, 0.00, 14.00, 'Normal', 3, 'Stress affects us all differently, however, you seem to have the ability to handle it well. You tend to stay excited about life in general and have a positive attitude towards various challenges. Your closed ones seem be proud of you since you might understand your responsibilities and try to stand by your values. It appears that you are confident about your skills and capability, hence, you would be performing well at your workplace. It seems that you do not tend to dwell in arguments and quarrels and try to handle difficult situations calmly. You seem to be taking work pressure lightly. If there is loads of work and tight deadlines, it appears that you plan it well and then execute to finish work on time. You seem to maintain balance in your personal and professional life. Your physiological state appears to be in a good shape as well. \r\n', 'inverse', 1, 1, NULL, '2021-02-04 20:00:39', '2021-02-04 20:00:39');
        INSERT INTO `report_characteristics` VALUES(12, 15.00, 18.00, 'Mild', 3, 'Stress affects all of us at some point in our lives, however, you seem to have the ability to handle it well. You appear be an active person who manages house chores and daily work efficiently. Your sleep quality seems to be satisfactory. You seem to be waking up fresh most of the days. Of late, you might get a headache due to stress at home or work. You seem to be diligent, thorough and extremely attentive to the details, hence, your ability to make quick decisions might be affected. You seem to perform very well in a team and do not get apprehensive about your performance.Seldom,stress might get to you and you might end up feeling drained.\r\n', 'inverse', 1, 1, NULL, '2021-02-04 20:00:39', '2021-02-04 20:00:39');
        INSERT INTO `report_characteristics` VALUES(13, 19.00, 25.00, 'Moderate', 3, 'You seem to be an optimistic person who strives towards his/her goals and is hopeful about the future. You seem to perform well at work and might need to stick to a strict schedule. Being competitive could be one of your virtues as it seems to help you in achieving more.\r\n \r\nSometimes you might get overwhelmed with work and try to do everything at once. From time to time you might also suffer from sleepless nights, which might lead to a headache. Your friends or one of your family members might have casually asked you to take it lightly and relax. Since it seems that you have high expectations from yourself, you can feel discouraged if you are unable to achieve your goals. Sometimes, you might even take a lot of pressure on yourself and end up losing your appetite.   \r\n\r\n', 'inverse', 1, 1, NULL, '2021-02-04 20:00:39', '2021-02-04 20:00:39');
        INSERT INTO `report_characteristics` VALUES(14, 26.00, 33.00, 'Severe', 3, 'You must be wondering why you are feeling worn out constantly. Your efficiency to perform tasks at work and daily chores might have also reduced significantly. You might be getting agitated and frustrated because of this. One of your friends or a family member must have shown concern towards your behaviour. It is a possibility that because of this constant sense of worry you are unable to sleep most of the nights in a week. There could be a drop in your appetite too. You might be suffering from a terrible headache which does not seem to go away. All of this, collectively, could have affected your ability to understand and perform tasks.\r\n', 'inverse', 1, 1, NULL, '2021-02-04 20:00:39', '2021-02-04 20:00:39');
        INSERT INTO `report_characteristics` VALUES(15, 34.00, 200.00, 'Extremely Severe', 3, 'You could be having a hard time paying heed to the responsibilities at work and home. Your sleeping and eating pattern might have been significantly affected. There is a possibility that you aren’t able to attend your work.Your colleagues and head of the team might be noticing change in your performance and may have shared with you the same which could be hampering your confidence. You might be feeling demotivated to do even the things you are passionate about. Your close friends or a family member might have also mentioned about your growing tendency of indecisiveness and lack in patience.\r\n', 'inverse', 1, 1, NULL, '2021-02-04 20:00:39', '2021-02-04 20:00:39');
        INSERT INTO `report_characteristics` VALUES(16, 6.00, 7.00, 'Normal', 4, 'Balancing personal and professional life can be tough at times but it seems that you are able to deal with it adequately. Sometimes you can feel a little overwhelmed, it’s natural. However, it appears that you do not  get discouraged to pursue your goals. Your skill-set seems to be as per the job requirement. Hence, you appear to enjoy working without getting exhausted. Your work-life balance seems to be satisfactory and you are able to enjoy time with friends & family and engaging in group activities. The pressure at work seems to not affect you adversely. It appears to work as a catalyst for enhancing your performance. It seems that you are able to organize the work at office efficiently and complete the tasks in the given time. \r\n', 'inverse', 1, 1, NULL, '2021-02-04 20:00:39', '2021-02-04 20:00:39');
        INSERT INTO `report_characteristics` VALUES(17, 8.00, 13.00, 'Mild', 4, 'It seems that you are performing well at work. Your skills and aptitude appear to be as per the requirement of the job. The pressure at work seems to motivate you to be more efficient. You seem to set high standards for yourself. Of late, you might feel discouraged if you are unable to stand on your expectations. You tend to manage your work-life balance well. You seem to be satisfied with your personal life as well.\r\n\r\nJob burnout is a kind of work-related stress. It might affect you once in a blue moon, but mostly, you seem to be able to handle it with optimism.\r\n', 'inverse', 1, 1, NULL, '2021-02-04 20:00:39', '2021-02-04 20:00:39');
        INSERT INTO `report_characteristics` VALUES(18, 14.00, 20.00, 'Moderate', 4, 'It seems that you are efficient and a great team player in your office. Your experience, skills and aptitude seems to suit the job role. It appears that you set high standards for yourself, which helps you to be productive. Sometimes, you might feel exhausted and disheartened if you are unable to achieve your goals. Mostly, you seem to be an optimistic person but occasionally you might get under pressure. It might cause some stress which can lead to sleep disturbance.\r\n \r\nJob burnout is distress related to work. Usually, you can manage it appropriately but sometimes it can get to you. On those days, you might lack the motivation to start the work and the level of concentration and attention might also dip.\r\n\r\n', 'inverse', 1, 1, NULL, '2021-02-04 20:00:39', '2021-02-04 20:00:39');
        INSERT INTO `report_characteristics` VALUES(19, 21.00, 24.00, 'Severe', 4, 'Professional life can be too demanding at times. It is also possible that you might be giving it all to please your colleagues and managers. You might be working overtime because of the high workload. It might lead to an imbalance in your personal and professional life. You might have very little or no time for yourself. It might cause exhaustion. \r\n', 'inverse', 1, 1, NULL, '2021-02-04 20:00:39', '2021-02-04 20:00:39');
        INSERT INTO `report_characteristics` VALUES(20, 25.00, 30.00, 'Extremely Severe', 4, 'Professional life can be too demanding at times. It is also possible that you are giving it your all to please the colleagues and managers. You might be working overtime because of the high workload. It might lead to an imbalance in your personal and professional life. This can cause exhaustion as you might be having very little or no time for yourself. It is also possible that it is leading to poor performance. It might also affect your emotional and mental health. \r\n', 'inverse', 1, 1, NULL, '2021-02-04 20:00:39', '2021-02-04 20:00:39');
        INSERT INTO `report_characteristics` VALUES(21, 281.00, 300.00, 'Extremely Happy', 5, 'You appear to be a happy and positive person. You seem to be an inspiration to others. It appears that you live in the present instead of dwelling in the past or future. You seem to have faith in your abilities and do not spend time worrying if you are good enough or not. Doubts and apprehensions do not seem to weigh you down. It appears that you also like to spend quality time with your friends and family. You seem to be adaptable and not worry much about life’s unpredictability. Optimism appears to be one of your greatest virtues. You tend to look at the positives instead of searching for faults.\r\n', 'straight', 1, 1, NULL, '2021-02-04 20:00:39', '2021-02-04 20:00:39');
        INSERT INTO `report_characteristics` VALUES(22, 251.00, 280.00, 'Happy', 5, 'You seem to be a happy soul. It appears that you spread happiness and others like to be around you. You seem to be an optimistic person who focuses on the positive aspects of life. Apprehensions and doubts do not seem to affect you. You appear to be living in the present instead of dwelling in past or future.\r\n', 'straight', 1, 1, NULL, '2021-02-04 20:00:39', '2021-02-04 20:00:39');
        INSERT INTO `report_characteristics` VALUES(23, 200.00, 250.00, 'Moderately Happy', 5, 'You seem to be a happy person but sometimes you might get affected by a few things in your environment. For instance, if someone criticizes you regarding your work, you might feel low for some time. You tend to stand right up instead of lamenting over something that didn’t go your way. It seems that you try to keep your spirits up by making changes in your lifestyle.\r\n', 'straight', 1, 1, NULL, '2021-02-04 20:00:39', '2021-02-04 20:00:39');
        INSERT INTO `report_characteristics` VALUES(24, 0.00, 199.00, 'Unhappy', 5, 'Your happiness might be getting affected by your environment. It seems that you give priority to others first instead of yourself. You might be trying to please people around you so that they have a good perception of you. That might need you to go an extra mile and sometimes out of your comfort zone. You might get discouraged if you hear a negative perception of yourself. There is a tendency to dwell in past or future instead of living in the moment. You might also get affected by apprehensions and self-doubt.\r\n', 'straight', 1, 1, NULL, '2021-02-04 20:00:39', '2021-02-04 20:00:39');
        INSERT INTO `report_characteristics` VALUES(25, 0.00, 11.00, 'Normal', 6, 'You use the Internet adequately and do not allow it to hamper your daily life. You might be comfortable even when you don’t access your phone or social media regularly. The chances are that you use the Internet for knowledge and enhancing your performance. Even if your smartphone doesn’t have an internet connection, you seem to not get affected by it.', 'inverse', 1, 1, NULL, '2021-02-04 20:00:39', '2021-02-04 20:00:39');
        INSERT INTO `report_characteristics` VALUES(26, 12.00, 17.00, 'Mild', 6, 'You seem to be aware of the pros and cons of using the internet. It appears that you usually utilize the internet for getting information. You seem to spend some time on social media as well.\r\nOf late, you might be using the internet more than usual. You might tend to indulge without realizing the limitations of your screen time. However, it seems that you can control your usage once you know that it’s affecting your day to day life and work performance.\r\n', 'inverse', 1, 1, NULL, '2021-02-04 20:00:39', '2021-02-04 20:00:39');
        INSERT INTO `report_characteristics` VALUES(27, 18.00, 28.00, 'Moderate', 6, 'You seem to be aware of the pros and cons of using the internet. You might have also noticed that your internet consumption is increasing gradually. It seems that you have taken measures to restrict your usage. You appear to be quite active on social media. It might be your escape from your real life. It seems that you enjoy engaging and talking to people online.\r\nSometimes you might use the internet more than usual. There could have been an instance where one of your family members poked you regarding your internet indulgence. It might have irritated you. From time to time, you might want to spend extra time on the internet. It can lead you to lose interest in your job. It might affect your work performance.\r\n', 'inverse', 1, 1, NULL, '2021-02-04 20:00:39', '2021-02-04 20:00:39');
        INSERT INTO `report_characteristics` VALUES(28, 29.00, 35.00, 'Severe', 6, 'In an era where the internet is so easily accessible, it is easy to go with the flow. You might be using the internet more than usual and it might have started affecting your personal and professional life. You might not be interested in your education, career or job. It might be getting difficult for you to assess the consequences of overconsumption of the internet. Social media might be your escape from the real world. You might genuinely like engaging in online conversations instead of talking to people in real life. There could have been an instance where one of your family members poked you regarding your indulgence in social media and that might have irritated you.\r\n', 'inverse', 1, 1, NULL, '2021-02-04 20:00:39', '2021-02-04 20:00:39');
        INSERT INTO `report_characteristics` VALUES(29, 36.00, 40.00, 'Very High', 8, 'Self-esteem refers to your sense of self-worth and personal value. In other words, it means how much you appreciate or like yourself. Very high self-esteem indicates that you are confident about your appearance, beliefs, emotions and behaviours.\r\n\r\nYou seem to have an adequate level of self-worth and a positive approach towards yourself. Strong principles and values seem to be your guiding force. Some of these values could be honest, trust, integrity, etc. You seem to have an inner drive to succeed. You tend to focus on your strengths and seem to be confident about your skills.', 'inverse', 1, 1, NULL, '2021-02-04 20:00:39', '2021-02-04 20:00:39');
        INSERT INTO `report_characteristics` VALUES(30, 31.00, 35.00, 'High', 8, 'Self-esteem refers to your sense of self-worth and personal value. In other words, it means how much you appreciate or like yourself. Your high self-esteem indicates that you seem to see yourself in a positive light. You appear to be confident in your appearance, beliefs, emotions and behaviour.\r\n\r\nYou seem to be adaptable and open to new challenges and changes. It is your self-worth and confidence that helps you to eradicate any apprehensions or adversities.', 'inverse', 1, 1, NULL, '2021-02-04 20:00:39', '2021-02-04 20:00:39');
        INSERT INTO `report_characteristics` VALUES(31, 26.00, 30.00, 'Average', 8, 'You seem to be a confident person who tries to have a positive outlook on life. There could be a sense of self-worth and self-appreciation. You seem to be guided by a set of strong principles and values. Your perception of yourself appears to be clear and positive. It seems to help you sail through the tough times.\r\nOf late,you might get anxious and doubtful in a stressful situation. However, it does not seem to affect your self-esteem.', 'inverse', 1, 1, NULL, '2021-02-04 20:00:39', '2021-02-04 20:00:39');
        INSERT INTO `report_characteristics` VALUES(32, 16.00, 25.00, 'Low', 8, 'Things might not be looking great in the office or at home due to possible lack of in your confidence level and feeling inferior to others. Regardless of the skills or talent you carry, you might doubt yourself and fear the judgment of others. There could be a lot of confusion and it might seem like you are experiencing some sort of a crisis. ', 'inverse', 1, 1, NULL, '2021-02-04 20:00:39', '2021-02-04 20:00:39');
        INSERT INTO `report_characteristics` VALUES(33, 10.00, 15.00, 'VeryLow', 8, 'A very low self-esteem indicates that you might be having some sort of trouble in establishing your identity. This might lead to inferiority complex and negative self-worth and self-evaluations. Recently, you might be finding it tough to strive for the best. You can feel that you are not enough. This might cause some trouble in your personal and professional life. Your friends or someone from your family might have mentioned that you are too rigid and that makes it difficult to deal with you. ', 'inverse', 1, 1, NULL, '2021-02-04 20:00:39', '2021-02-04 20:00:39');
        INSERT INTO `report_characteristics` VALUES(34, 0.00, 14.00, 'Normal', 9, 'You seem to nurture confidence and peace in your day to day life. Challenges in personal and occupational life seem to motivate you to achieve your goals. It appears that you have a good concentration level and might not get anxious frequently. You seem to be committed to a higher purpose in life, which helps you in becoming a better person each day. You seem to be able to handle difficult situations in life with vigour and a tranquil mind', 'inverse', 1, 1, NULL, '2021-02-04 20:00:39', '2021-02-04 20:00:39');
        INSERT INTO `report_characteristics` VALUES(35, 15.00, 24.00, 'Has State Anxiety', 9, 'State anxiety appears when an individual faces an unpleasant event. It can be a temporary feeling or emotion.\r\nYou seem to be a calm and composed person. It appears that you stay relaxed in day to day life. You seem to have the ability to handle difficult emotions. \r\nSometimes, unpleasant situations might get to you. The personal or work-related challenge might overwhelm you. It might affect your mood, sleep pattern, attention and concentration. The discomfort might subside when the current challenge is alleviated.', 'inverse', 1, 1, NULL, '2021-02-04 20:00:39', '2021-02-04 20:00:39');
        INSERT INTO `report_characteristics` VALUES(36, 0.00, 14.00, 'Normal', 10, 'You seem to be able to handle stressful situations aptly, without getting anxious. You seem to be confident and have a positive attitude in your day to day life. Challenges at home or work seem to not affect you adversely. You seem to have a healthy sleep schedule and can sleep peacefully without any tension. Even if you face difficult or stressful situations, it appears that you think thoroughly and calmly instead of panicking. You seem to not dwell in arguments and try to focus on the solution rather than thinking about the problem. You seem to have a good work-life balance', 'inverse', 1, 1, NULL, '2021-02-04 20:00:39', '2021-02-04 20:00:39');
        INSERT INTO `report_characteristics` VALUES(37, 15.00, 24.00, 'Has Trait Anxiety', 10, 'You seem to seek security and safety in your life. Hence, looking out for threats could be a frequent exercise.  \r\nIf you sense any disturbance, you might start getting anxious for the sake of your protection. Anxiety is a reflex action to help you survive. When you face an unpleasant situation, you might experience physiological changes like palpitations and sweaty hands. It might affect your performance and ability to deal with challenges.', 'inverse', 1, 1, NULL, '2021-02-04 20:00:39', '2021-02-04 20:00:39');
        INSERT INTO `report_characteristics` VALUES(38, 1.00, 2.99, 'Low Resilience', 11, 'You seem to be a positive and efficient person. It appears that you can bounce back after a crisis. \r\nSometimes you might find it hard to deal with a recent or significant setback. You might overthink about various situations and their adverse outcomes. It might affect the way you think and plan for the future. Your potential to bounce back might not be adequate. There is a possibility of getting depressive thoughts and mood swings. ', 'straight', 1, 1, NULL, '2021-02-04 20:00:39', '2021-02-04 20:00:39');
        INSERT INTO `report_characteristics` VALUES(39, 3.00, 4.30, 'Normal Resilience', 11, 'You seem to be a realist and can look at things as they are in life. It appears that you can deal with adversities practically. You seem to not be in denial for long and start thinking of the next step required to get out of the setback. You seem to be able to deal with life’s adverse situations adequately.', 'straight', 1, 1, NULL, '2021-02-04 20:00:39', '2021-02-04 20:00:39');
        INSERT INTO `report_characteristics` VALUES(40, 4.31, 5.00, 'High Resilience', 11, 'Resilience is the capacity to recover from difficult events. You seem to have an ability to with stand adversity and bounce back despite life’s downturns. Restarting after a setback seems to be not so difficult for you, however, it might be emotionally draining. Your coping mechanism seems to be helping you to start, think or plan again. ', 'straight', 1, 1, NULL, '2021-02-04 20:00:39', '2021-02-04 20:00:39');
        INSERT INTO `report_characteristics` VALUES(41, 42.00, 50.00, 'Very High', 12, 'Job satisfaction refers to the feeling of fulfilment or enjoyment you might drive from your job. It seems that you are very satisfied with your job. Your job role appears to be suiting your skill-set and area of interest. You seem to have a great relationship with your employer as well. It appears that you have a good work-life balance. When you are able to achieve goals or objectives, you seem to be proud and satisfied. It appears that you value your job highly. ', 'straight', 1, 1, NULL, '2021-02-04 20:00:39', '2021-02-04 20:00:39');
        INSERT INTO `report_characteristics` VALUES(42, 39.00, 41.00, 'High', 12, 'Job satisfaction refers to the feeling of fulfilment or enjoyment you might drive from your job. You seem to be satisfied with your company and conform to their values. It appears that you have a good relationship with your employer. Your job role seems to suit your skill-set and passion. You seem to be always talking highly about your workplace. Since you seem to be satisfied with your job, it acts as a motivator to work hard and achieve the goals. It appears that you value your job highly.', 'straight', 1, 1, NULL, '2021-02-04 20:00:39', '2021-02-04 20:00:39');
        INSERT INTO `report_characteristics` VALUES(43, 32.00, 38.00, 'Average', 12, 'Job satisfaction refers to the feeling of fulfilment or enjoyment you might drive from your job. You seem to like your work but might be having concerns in your workplace. It might also be possible that you are looking to switch your job. Some changes might be required for you to perform well in the current role. You seem to handle work-related stress well and generally feel comfortable with your colleagues. ', 'straight', 1, 1, NULL, '2021-02-04 20:00:39', '2021-02-04 20:00:39');
        INSERT INTO `report_characteristics` VALUES(44, 27.00, 31.00, 'Low', 12, 'Job dissatisfaction refers to a situation when an employee is unhappy with their job. You seem to be a hard-working person but might not be very satisfied with your job. There can be various reason for your unhappiness. You might be underpaid, limited career growth, lack of interest in your work or no support from your manager. You might feel a little discouraged and working might feel like a burden', 'straight', 1, 1, NULL, '2021-02-04 20:00:39', '2021-02-04 20:00:39');
        INSERT INTO `report_characteristics` VALUES(45, 10.00, 26.00, 'Very Low', 12, 'Job dissatisfaction refers to a situation when an employee is unhappy with their job. You seem to be a hard-working person but might not be very satisfied with your job. There can be various reason for your unhappiness. You might be underpaid, limited career growth, lack of interest in your work or no support from your manager. You might feel discouraged. Working might feel like a burden. You might not even be able to perform to your fullest potential. ', 'straight', 1, 1, NULL, '2021-02-04 20:00:39', '2021-02-04 20:00:39');
        INSERT INTO `report_characteristics` VALUES(46, 1.00, 100.00, 'Substance Abuse Disorder Exists', 13, '', 'inverse', 1, 1, NULL, '2021-02-04 20:00:39', '2021-02-04 20:00:39');
        INSERT INTO `report_characteristics` VALUES(47, 0.00, 0.00, 'Substance Abuse Disorder Exists', 13, '', 'inverse', 1, 1, NULL, '2021-02-04 20:00:39', '2021-02-04 20:00:39');
        INSERT INTO `report_characteristics` VALUES(48, 0.00, 0.00, '', 7, 'You seem to be a considerate and thoughtful person who tends to give a lot of love and attention to people around. You might be expecting the same treatment in return. However, it might not be possible for everyone to be available for you all the time. Sometimes, it might hurt and you tend to start keeping a distance from such people. Some people might even perceive that it is hard to communicate with you. However, you might be protecting yourself from getting hurt.\r\nThe sense of self-protection might even extend to your interpersonal relationships. Hence, you might be a little vigilant in your relationships. In a situation, when someone is nice to you, you seem to make sure if their intention is in the right place and they are not trying to take advantage of you.\r\nYou seem to be sentimental. In an unfavourable situation, you might get a little anxious. At times, it can affect your daily activities.\r\nIt appears that you have high self-esteem. Therefore, it might be a little difficult for you to deal with refusals or criticism.\r\nThe sense of self-protection might be rooting for your survival instinct but it might hinder your ability to develop new relationships.\r\n  ', 'straight', 0, 0, NULL, NULL, NULL);
        INSERT INTO `report_characteristics` VALUES(49, 0.00, 0.00, '', 14, 'You seem to have a higher purpose in life. Hence, you might not conform to the rules of society. You seem to be devoted to achieving your revolutionary goals. Your closed ones might feel that you are ignoring their emotional needs and responsibilities.\r\n\r\nYou seem to have leadership qualities. Sometimes, it might get difficult for you to accept criticism. You might be a little uncomfortable while dealing with unfavourable situations.\r\n\r\nYou seem to believe that you are on the right path. Even if you have to do something that is out of your comfort zone, you might do it without feeling guilty.\r\n\r\nSince you seem to be so engrossed in your cause, you might feel disconnected from others. You might think that people are unable to understand your purpose. It might affect your interpersonal relationships and lead to rough situations.', 'straight', 0, 0, NULL, NULL, NULL);
        INSERT INTO `report_characteristics` VALUES(50, 0.00, 0.00, '', 15, 'You seem to be a sensitive person and might easily be affected by criticism. You might be unable to handle stressful situations and keep calm. It leads to increased vulnerability and there could be thoughts of self-harm. You might be having troubles in your relationships due to all of these issues.', 'straight', 0, 0, NULL, NULL, NULL);
        INSERT INTO `report_characteristics` VALUES(51, 0.00, 0.00, '', 16, 'You seem to be particular and selective about your needs and wants, which might cause confusion and dilemma at times. You seem to be exploring your identity and sexuality as you might be unsure about it. Your relationships seem to be intense; however, your partners might have not been able to fulfil your emotional needs. Due to unsuccessful relationships, you might feel hollow or disconnect from people around you. Some problematic behaviours might be recurring due to which you might face adjustment problems in your relationships. ', 'straight', 0, 0, NULL, NULL, NULL);
        INSERT INTO `report_characteristics` VALUES(52, 0.00, 0.00, '', 17, 'You might be an emotional and expressive person due to which some people might think that you could be seeking attention.\r\nYou seem to be receptive of other\'s opinions and thoughts. Sometimes, you might change your decision at the last moment. Hence, people might think you are indecisive. It might lead to problems in your personal, marital and occupational setup.\r\nYou seem to be confident in your skin. If someone compliments on your physical appearance, you seem to like it.', 'straight', 0, 0, NULL, NULL, NULL);
        INSERT INTO `report_characteristics` VALUES(53, 0.00, 0.00, '', 19, 'You seem to like following a routine and might not appreciate any changes in your schedule. It appears that you are an ambitious person who tries to be better than people around themself.\r\nYou seem to give your best so that your colleagues and managers appreciate you. Sometimes, you might not be able to take criticism healthily. \r\nYou seem to focus on your work rather than investing time in group activities or discussions. Hence, some people might perceive you are unsocial. At your home, you might not like to engage in small talk. It might be affecting your interpersonal relationships. Your family members might want to talk to you. However, you might be unable to reciprocate with the same intensity of emotions. \r\nYou seem to be a responsible person who seeks security in all the spheres of life.  ', 'straight', 0, 0, NULL, NULL, NULL);
        INSERT INTO `report_characteristics` VALUES(54, 0.00, 0.00, '', 20, 'You seem to have a friendly and welcoming personality. It appears that you seek advice from your friends and family before taking any important decision in your life. You seem to be obedient and might not question authority. It appears that you like to go with the flow. \r\nYou seem to be kind and helpful. It might be difficult for you to say no to your closed ones.\r\nYou seem to be very attached to your friends and family and sometimes, might even fear of losing them. It might seem to you like you will be left alone. You might not be comfortable with that thought. \r\nSome people might even perceive you as an under-confident person because you seek reassurance.', 'straight', 0, 0, NULL, NULL, NULL);
        INSERT INTO `report_characteristics` VALUES(55, 0.00, 0.00, '', 18, 'Perfectionism seems to be one of your greatest virtues. You tend to spend extra time perfecting even the smallest details. It appears that your skills match your job role and you try to give your best. Sometimes, you might feel that you are not performing up to the mark. You might even doubt the quality of your work. Everything comes secondary to your need of being perfect. It might affect your interpersonal relationships. \r\nYou seem to have high standards which might not be possible for everyone to achieve in your team. Hence, you might across as someone very particular. Other employees might find it hard to match up to your expectations', 'straight', 0, 0, NULL, NULL, NULL);

        ");
        DB::unprepared("
        INSERT INTO `rating_pictures` VALUES(1, 1, 'happy.png', NULL, NULL, NULL);
INSERT INTO `rating_pictures` VALUES(2, 2, 'smile.png', NULL, NULL, NULL);
INSERT INTO `rating_pictures` VALUES(3, 3, 'neutral.png', NULL, NULL, NULL);
INSERT INTO `rating_pictures` VALUES(4, 4, 'sad.png', NULL, NULL, NULL);
INSERT INTO `rating_pictures` VALUES(5, 5, 'verysad.png', NULL, NULL, NULL);
INSERT INTO `rating_pictures` VALUES(6, 6, 'happy.png', NULL, NULL, NULL);
INSERT INTO `rating_pictures` VALUES(7, 7, 'smile.png', NULL, NULL, NULL);
INSERT INTO `rating_pictures` VALUES(8, 8, 'neutral.png', NULL, NULL, NULL);
INSERT INTO `rating_pictures` VALUES(9, 9, 'sad.png', NULL, NULL, NULL);
INSERT INTO `rating_pictures` VALUES(10, 10, 'verysad.png', NULL, NULL, NULL);
INSERT INTO `rating_pictures` VALUES(11, 11, 'happy.png', NULL, NULL, NULL);
INSERT INTO `rating_pictures` VALUES(12, 12, 'smile.png', NULL, NULL, NULL);
INSERT INTO `rating_pictures` VALUES(13, 13, 'neutral.png', NULL, NULL, NULL);
INSERT INTO `rating_pictures` VALUES(14, 14, 'sad.png', NULL, NULL, NULL);
INSERT INTO `rating_pictures` VALUES(15, 15, 'verysad.png', NULL, NULL, NULL);
INSERT INTO `rating_pictures` VALUES(16, 16, 'happy.png', NULL, NULL, NULL);
INSERT INTO `rating_pictures` VALUES(17, 17, 'smile.png', NULL, NULL, NULL);
INSERT INTO `rating_pictures` VALUES(18, 18, 'neutral.png', NULL, NULL, NULL);
INSERT INTO `rating_pictures` VALUES(19, 19, 'sad.png', NULL, NULL, NULL);
INSERT INTO `rating_pictures` VALUES(20, 20, 'verysad.png', NULL, NULL, NULL);
INSERT INTO `rating_pictures` VALUES(21, 21, 'happy.png', NULL, NULL, NULL);
INSERT INTO `rating_pictures` VALUES(22, 22, 'smile.png', NULL, NULL, NULL);
INSERT INTO `rating_pictures` VALUES(23, 23, 'neutral.png', NULL, NULL, NULL);
INSERT INTO `rating_pictures` VALUES(24, 24, 'verysad.png', NULL, NULL, NULL);
INSERT INTO `rating_pictures` VALUES(25, 25, 'happy.png', NULL, NULL, NULL);
INSERT INTO `rating_pictures` VALUES(26, 26, 'smile.png', NULL, NULL, NULL);
INSERT INTO `rating_pictures` VALUES(27, 27, 'neutral.png', NULL, NULL, NULL);
INSERT INTO `rating_pictures` VALUES(28, 28, 'verysad.png', NULL, NULL, NULL);
INSERT INTO `rating_pictures` VALUES(29, 29, 'happy.png', NULL, NULL, NULL);
INSERT INTO `rating_pictures` VALUES(30, 30, 'smile.png', NULL, NULL, NULL);
INSERT INTO `rating_pictures` VALUES(31, 31, 'neutral.png', NULL, NULL, NULL);
INSERT INTO `rating_pictures` VALUES(32, 32, 'sad.png', NULL, NULL, NULL);
INSERT INTO `rating_pictures` VALUES(33, 33, 'verysad.png', NULL, NULL, NULL);
INSERT INTO `rating_pictures` VALUES(34, 34, 'happy.png', NULL, NULL, NULL);
INSERT INTO `rating_pictures` VALUES(35, 35, NULL, NULL, NULL, NULL);
INSERT INTO `rating_pictures` VALUES(36, 36, 'happy.png', NULL, NULL, NULL);
INSERT INTO `rating_pictures` VALUES(37, 37, NULL, NULL, NULL, NULL);
INSERT INTO `rating_pictures` VALUES(38, 38, 'verysad.png', NULL, NULL, NULL);
INSERT INTO `rating_pictures` VALUES(39, 39, 'neutral.png', NULL, NULL, NULL);
INSERT INTO `rating_pictures` VALUES(40, 40, 'happy.png', NULL, NULL, NULL);
INSERT INTO `rating_pictures` VALUES(41, 41, 'happy.png', NULL, NULL, NULL);
INSERT INTO `rating_pictures` VALUES(42, 42, 'smile.png', NULL, NULL, NULL);
INSERT INTO `rating_pictures` VALUES(43, 43, 'neutral.png', NULL, NULL, NULL);
INSERT INTO `rating_pictures` VALUES(44, 44, 'sad.png', NULL, NULL, NULL);
INSERT INTO `rating_pictures` VALUES(45, 45, 'verysad.png', NULL, NULL, NULL);
INSERT INTO `rating_pictures` VALUES(46, 46, NULL, NULL, NULL, NULL);
INSERT INTO `rating_pictures` VALUES(47, 47, NULL, NULL, NULL, NULL);
INSERT INTO `rating_pictures` VALUES(48, 48, NULL, NULL, NULL, NULL);
INSERT INTO `rating_pictures` VALUES(49, 49, NULL, NULL, NULL, NULL);
INSERT INTO `rating_pictures` VALUES(50, 50, NULL, NULL, NULL, NULL);
INSERT INTO `rating_pictures` VALUES(51, 51, NULL, NULL, NULL, NULL);
INSERT INTO `rating_pictures` VALUES(52, 52, NULL, NULL, NULL, NULL);
INSERT INTO `rating_pictures` VALUES(53, 53, NULL, NULL, NULL, NULL);
INSERT INTO `rating_pictures` VALUES(54, 54, NULL, NULL, NULL, NULL);
INSERT INTO `rating_pictures` VALUES(55, 48, NULL, NULL, NULL, NULL);
        ");
    }
}
