<?php

namespace Database\Seeders;

use Illuminate\Database\Seeder;
use Illuminate\Support\Facades\DB;

class QuestionSeeder extends Seeder
{
    /**
     * Run the database seeds.
     *
     * @return void
     */
    public function run()
    {
        DB::transaction(function () {
            //             DB::unprepared("
            //         INSERT INTO `questions` VALUES(1, 'Mostly i have fun and enjoyment in my life', 21, NULL, NULL, NULL);
            //         INSERT INTO `questions` VALUES(2, 'I dont like others offending me and do not react well in such situation', 7, NULL, NULL, NULL);
            //         INSERT INTO `questions` VALUES(3, 'i do not get in to too many details', 18, NULL, NULL, NULL);
            //         INSERT INTO `questions` VALUES(4, 'I am not sure what kind of person i want to be', 16, NULL, NULL, NULL);
            //         INSERT INTO `questions` VALUES(5, 'I express my feelings so that everyone can see', 17, NULL, NULL, NULL);
            //         INSERT INTO `questions` VALUES(6, 'I allow other people to take my life\'s major descisions', 20, NULL, NULL, NULL);
            //         INSERT INTO `questions` VALUES(7, 'I usually feel nervous or tense', 19, NULL, NULL, NULL);
            //         INSERT INTO `questions` VALUES(8, 'I never get angry about anything', 21, NULL, NULL, NULL);
            //         INSERT INTO `questions` VALUES(9, 'I go to extremes to try to keep people from abandoning me', 16, NULL, NULL, NULL);
            //         INSERT INTO `questions` VALUES(10, 'I am very cautious in my life and activities', 18, NULL, NULL, NULL);
            //         INSERT INTO `questions` VALUES(11, 'I have never faced legal action', 14, NULL, NULL, NULL);
            //         INSERT INTO `questions` VALUES(12, 'People find me less expressive and detached', 21, NULL, NULL, NULL);
            //         INSERT INTO `questions` VALUES(13, 'I get into short lasting intense relationships', 16, NULL, NULL, NULL);
            //         INSERT INTO `questions` VALUES(14, 'I generally find good and honest people around me', 7, NULL, NULL, NULL);
            //         INSERT INTO `questions` VALUES(15, 'with people on whom I depend a lot, I find it hard to disagree', 20, NULL, NULL, NULL);
            //         INSERT INTO `questions` VALUES(16, 'I feel uncomfortable in social situations, crowded party etc', 19, NULL, NULL, NULL);
            //         INSERT INTO `questions` VALUES(17, 'I get too easily influences by what\'s happening around me', 17, NULL, NULL, NULL);
            //         INSERT INTO `questions` VALUES(18, 'When I hurt or mistreat someone, I usually feel bad', 14, NULL, NULL, NULL);
            //         INSERT INTO `questions` VALUES(19, 'I get agressive (verbally or physically if anyone tries to obstruct in my way', 15, NULL, NULL, NULL);
            //         INSERT INTO `questions` VALUES(20, 'At times I\'ve refused to hold a job or responsibility, when it was', 14, NULL, NULL, NULL);
            //         INSERT INTO `questions` VALUES(21, 'I don\'t show my reaction when someone praises or criticizes me', 21, NULL, NULL, NULL);
            //         INSERT INTO `questions` VALUES(22, 'For years I have kept hard feelings against people', 7, NULL, NULL, NULL);
            //         INSERT INTO `questions` VALUES(23, 'I seek perfection even if it means spending extra time on things', 18, NULL, NULL, NULL);
            //         INSERT INTO `questions` VALUES(24, 'People often ridicule me in my absence', 7, NULL, NULL, NULL);
            //         INSERT INTO `questions` VALUES(25, 'I have never threatened suicide or knowingly harmed myself', 16, NULL, NULL, NULL);
            //         INSERT INTO `questions` VALUES(26, 'I switch between my feelings very frequently', 17, NULL, NULL, NULL);
            //         INSERT INTO `questions` VALUES(27, 'Even if people don\'t like it, I will fight for my rights', 7, NULL, NULL, NULL);
            //         INSERT INTO `questions` VALUES(28, 'I like to dress to get noticed in a group of people', 17, NULL, NULL, NULL);
            //         INSERT INTO `questions` VALUES(29, 'i will lie or cheat to serve my purpose', 14, NULL, NULL, NULL);
            //         INSERT INTO `questions` VALUES(30, 'If I don\'t get results quickly, I change my plan', 14, NULL, NULL, NULL);
            //         INSERT INTO `questions` VALUES(31, 'I don\'t feel like having sex with anyone', 21, NULL, NULL, NULL);
            //         INSERT INTO `questions` VALUES(32, 'People find me strictly discplined and rules oriented', 18, NULL, NULL, NULL);
            //         INSERT INTO `questions` VALUES(33, 'Being alone makes me uncomfortable and helpless', 20, NULL, NULL, NULL);
            //         INSERT INTO `questions` VALUES(34, 'Until I am certain that people like me, I will not get involved with them', 19, NULL, NULL, NULL);
            //         INSERT INTO `questions` VALUES(35, 'I don\'t like to be center of attraction', 17, NULL, NULL, NULL);
            //         INSERT INTO `questions` VALUES(36, 'I suspect my spouse or partner is cheating on me', 7, NULL, NULL, NULL);
            //         INSERT INTO `questions` VALUES(37, 'Sometimes out of anger I break or throw things', 15, NULL, NULL, NULL);
            //         INSERT INTO `questions` VALUES(38, 'I have some very close friends from many years', 14, NULL, NULL, NULL);
            //         INSERT INTO `questions` VALUES(39, 'I constantly wonder that people around may not like me', 19, NULL, NULL, NULL);
            //         INSERT INTO `questions` VALUES(40, 'I often have feeling of emptiness inside me', 16, NULL, NULL, NULL);
            //         INSERT INTO `questions` VALUES(41, 'I am unnecerrarily preoccupied with perfection & productivity which', 18, NULL, NULL, NULL);
            //         INSERT INTO `questions` VALUES(42, 'I am afraid of living by myself, without anyone around', 20, NULL, NULL, NULL);
            //         INSERT INTO `questions` VALUES(43, 'A lot of things which don\'t bother others seem dangerous to me', 19, NULL, NULL, NULL);
            //         INSERT INTO `questions` VALUES(44, 'People see me as a flirt', 17, NULL, NULL, NULL);
            //         INSERT INTO `questions` VALUES(45, 'I don\'t ask favors from people I am close with', 20, NULL, NULL, NULL);
            //         INSERT INTO `questions` VALUES(46, 'I prefer solitory activities', 21, NULL, NULL, NULL);
            //         INSERT INTO `questions` VALUES(47, 'I get into physical fights after losing my temper', 14, NULL, NULL, NULL);
            //         INSERT INTO `questions` VALUES(48, 'I have a reputation of being too stiff or formal', 18, NULL, NULL, NULL);
            //         INSERT INTO `questions` VALUES(49, 'For routine decisions, I often depend on others\'s advice or reassurance', 20, NULL, NULL, NULL);
            //         INSERT INTO `questions` VALUES(50, 'Even if there are other people around, I keep to myself', 19, NULL, NULL, NULL);
            //         INSERT INTO `questions` VALUES(51, 'I often get into trouble', 14, NULL, NULL, NULL);
            //         INSERT INTO `questions` VALUES(52, 'I am sure there is a conspiracy behind many things in the world', 7, NULL, NULL, NULL);
            //         INSERT INTO `questions` VALUES(53, 'I get frequent mood swings', 15, NULL, NULL, NULL);
            //         INSERT INTO `questions` VALUES(54, 'I find it hard to adjust to new ways of doing things', 18, NULL, NULL, NULL);
            //         INSERT INTO `questions` VALUES(55, 'I am seen as a strange person by most people', 21, NULL, NULL, NULL);
            //         INSERT INTO `questions` VALUES(56, 'I love to take risks sometimes in life', 15, NULL, NULL, NULL);
            //         INSERT INTO `questions` VALUES(57, 'We need friends in our life to be happy', 21, NULL, NULL, NULL);
            //         INSERT INTO `questions` VALUES(58, 'I am more concerned about my own thoughts than what goes around me', 21, NULL, NULL, NULL);
            //         INSERT INTO `questions` VALUES(59, 'usually try to make people do things my way', 18, NULL, NULL, NULL);
            //         INSERT INTO `questions` VALUES(60, 'I can\'t experience any positive feeling in most scenarios', 1, NULL, NULL, NULL);
            //         INSERT INTO `questions` VALUES(61, 'I find it difficult to take initiative to do things.', 1, NULL, NULL, NULL);
            //         INSERT INTO `questions` VALUES(62, 'I feel that I have nothing to look forward to in life', 1, NULL, NULL, NULL);
            //         INSERT INTO `questions` VALUES(63, 'I feel discouraged & sad', 1, NULL, NULL, NULL);
            //         INSERT INTO `questions` VALUES(64, 'I am not enthusiastic about anything', 1, NULL, NULL, NULL);
            //         INSERT INTO `questions` VALUES(65, 'I feel I am not of much worth as a person.', 1, NULL, NULL, NULL);
            //         INSERT INTO `questions` VALUES(66, 'I feel that life is meaningless', 1, NULL, NULL, NULL);
            //         INSERT INTO `questions` VALUES(67, 'I am aware of dryness of my mouth or consistent thirst', 2, NULL, NULL, NULL);
            //         INSERT INTO `questions` VALUES(68, 'I experience breathing difficulty (eg, excessively rapid breathing, breathlessness even without physical exertion)', 2, NULL, NULL, NULL);
            //         INSERT INTO `questions` VALUES(69, 'I experience trembling/shaking (eg, in my hands/legs)', 2, NULL, NULL, NULL);
            //         INSERT INTO `questions` VALUES(70, 'I am worried about situations in which I might panic and make a fool of myself', 2, NULL, NULL, NULL);
            //         INSERT INTO `questions` VALUES(71, 'i feel i am about to experience panic.', 2, NULL, NULL, NULL);
            //         INSERT INTO `questions` VALUES(72, 'I am aware of the action of my heart even without physical exertion (eg, sense of heart rate increase, heart missing a beat)', 2, NULL, NULL, NULL);
            //         INSERT INTO `questions` VALUES(73, 'I am in constant fear of unknown', 2, NULL, NULL, NULL);
            //         INSERT INTO `questions` VALUES(74, 'I find it hard to cool down/ calm down.', 3, NULL, NULL, NULL);
            //         INSERT INTO `questions` VALUES(75, 'I frequently over-react to situations.', 3, NULL, NULL, NULL);
            //         INSERT INTO `questions` VALUES(76, 'I feel that I am using a lot of nervous energy', 3, NULL, NULL, NULL);
            //         INSERT INTO `questions` VALUES(77, 'I get agitated/angry easily', 3, NULL, NULL, NULL);
            //         INSERT INTO `questions` VALUES(78, 'I find it difficult to relax.', 3, NULL, NULL, NULL);
            //         INSERT INTO `questions` VALUES(79, 'I do not tolerate any distractions to my work in hand', 3, NULL, NULL, NULL);
            //         INSERT INTO `questions` VALUES(80, 'I feel I am oversensitive.', 3, NULL, NULL, NULL);
            //         INSERT INTO `questions` VALUES(81, 'I feel emotionally drained due to my work.', 4, NULL, NULL, NULL);
            //         INSERT INTO `questions` VALUES(82, 'I feel like my work is too much for me to handle.', 4, NULL, NULL, NULL);
            //         INSERT INTO `questions` VALUES(83, 'I feel tired when I get up in the morning  to face another day of work.', 4, NULL, NULL, NULL);
            //         INSERT INTO `questions` VALUES(84, 'I think due to my work/ office I have become less caring for my loved ones.', 4, NULL, NULL, NULL);
            //         INSERT INTO `questions` VALUES(85, 'By the end of the day, I start losing my patience', 4, NULL, NULL, NULL);
            //         INSERT INTO `questions` VALUES(86, 'I think during my work/office hours I accomplish may important things.', 4, NULL, NULL, NULL);
            // ");
            //             DB::unprepared("
            //         INSERT INTO `questions` VALUES(87, 'Qus', 7, NULL, NULL, NULL);
            //         INSERT INTO `questions` VALUES(88, 'Qus', 7, NULL, NULL, NULL);
            //         INSERT INTO `questions` VALUES(89, 'Qus', 7, NULL, NULL, NULL);
            //         INSERT INTO `questions` VALUES(90, 'Qus', 7, NULL, NULL, NULL);
            //         INSERT INTO `questions` VALUES(91, 'Qus', 7, NULL, NULL, NULL);
            //         INSERT INTO `questions` VALUES(92, 'Qus', 7, NULL, NULL, NULL);
            //         INSERT INTO `questions` VALUES(93, 'Qus', 7, NULL, NULL, NULL);
            //         INSERT INTO `questions` VALUES(94, 'Qus', 7, NULL, NULL, NULL);
            //         INSERT INTO `questions` VALUES(95, 'Qus', 7, NULL, NULL, NULL);
            //         INSERT INTO `questions` VALUES(96, 'Qus', 7, NULL, NULL, NULL);
            //         INSERT INTO `questions` VALUES(97, 'Qus', 7, NULL, NULL, NULL);
            //         INSERT INTO `questions` VALUES(98, 'Qus', 7, NULL, NULL, NULL);
            //         INSERT INTO `questions` VALUES(99, 'Qus', 7, NULL, NULL, NULL);
            //         INSERT INTO `questions` VALUES(100, 'Qus', 7, NULL, NULL, NULL);
            //         INSERT INTO `questions` VALUES(101, 'Qus', 7, NULL, NULL, NULL);
            //         INSERT INTO `questions` VALUES(102, 'Qus', 7, NULL, NULL, NULL);
            //         INSERT INTO `questions` VALUES(103, 'Qus', 7, NULL, NULL, NULL);
            //         INSERT INTO `questions` VALUES(104, 'Qus', 8, NULL, NULL, NULL);
            //         INSERT INTO `questions` VALUES(105, 'Qus', 8, NULL, NULL, NULL);
            //         INSERT INTO `questions` VALUES(106, 'Qus', 8, NULL, NULL, NULL);
            //         INSERT INTO `questions` VALUES(107, 'Qus', 8, NULL, NULL, NULL);
            //         INSERT INTO `questions` VALUES(108, 'Qus', 8, NULL, NULL, NULL);
            //         INSERT INTO `questions` VALUES(109, 'Qus', 8, NULL, NULL, NULL);
            //         INSERT INTO `questions` VALUES(110, 'Qus', 8, NULL, NULL, NULL);
            //         INSERT INTO `questions` VALUES(111, 'Qus', 8, NULL, NULL, NULL);
            //         INSERT INTO `questions` VALUES(112, 'Qus', 8, NULL, NULL, NULL);
            //         INSERT INTO `questions` VALUES(113, 'Qus', 8, NULL, NULL, NULL);
            //         INSERT INTO `questions` VALUES(114, 'Qus', 9, NULL, NULL, NULL);
            //         INSERT INTO `questions` VALUES(115, 'Qus', 9, NULL, NULL, NULL);
            //         INSERT INTO `questions` VALUES(116, 'Qus', 9, NULL, NULL, NULL);
            //         INSERT INTO `questions` VALUES(117, 'Qus', 9, NULL, NULL, NULL);
            //         INSERT INTO `questions` VALUES(118, 'Qus', 9, NULL, NULL, NULL);
            //         INSERT INTO `questions` VALUES(119, 'Qus', 9, NULL, NULL, NULL);
            //         INSERT INTO `questions` VALUES(120, 'Qus', 10, NULL, NULL, NULL);
            //         INSERT INTO `questions` VALUES(121, 'Qus', 10, NULL, NULL, NULL);
            //         INSERT INTO `questions` VALUES(122, 'Qus', 10, NULL, NULL, NULL);
            //         INSERT INTO `questions` VALUES(123, 'Qus', 10, NULL, NULL, NULL);
            //         INSERT INTO `questions` VALUES(124, 'Qus', 10, NULL, NULL, NULL);
            //         INSERT INTO `questions` VALUES(125, 'Qus', 10, NULL, NULL, NULL);
            //         INSERT INTO `questions` VALUES(126, 'Qus', 11, NULL, NULL, NULL);
            //         INSERT INTO `questions` VALUES(127, 'Qus', 11, NULL, NULL, NULL);
            //         INSERT INTO `questions` VALUES(128, 'Qus', 11, NULL, NULL, NULL);
            //         INSERT INTO `questions` VALUES(129, 'Qus', 11, NULL, NULL, NULL);
            //         INSERT INTO `questions` VALUES(130, 'Qus', 11, NULL, NULL, NULL);
            //         INSERT INTO `questions` VALUES(131, 'Qus', 11, NULL, NULL, NULL);
            //         INSERT INTO `questions` VALUES(132, 'Qus', 12, NULL, NULL, NULL);
            //         INSERT INTO `questions` VALUES(133, 'Qus', 12, NULL, NULL, NULL);
            //         INSERT INTO `questions` VALUES(134, 'Qus', 12, NULL, NULL, NULL);
            //         INSERT INTO `questions` VALUES(135, 'Qus', 12, NULL, NULL, NULL);
            //         INSERT INTO `questions` VALUES(136, 'Qus', 12, NULL, NULL, NULL);
            //         INSERT INTO `questions` VALUES(137, 'Qus', 12, NULL, NULL, NULL);
            //         INSERT INTO `questions` VALUES(138, 'Qus', 12, NULL, NULL, NULL);
            //         INSERT INTO `questions` VALUES(139, 'Qus', 12, NULL, NULL, NULL);
            //         INSERT INTO `questions` VALUES(140, 'Qus', 12, NULL, NULL, NULL);
            //         INSERT INTO `questions` VALUES(141, 'Qus', 12, NULL, NULL, NULL);
            //         INSERT INTO `questions` VALUES(142, 'Qus', 13, NULL, NULL, NULL);
            //         INSERT INTO `questions` VALUES(143, 'Qus', 13, NULL, NULL, NULL);
            //         INSERT INTO `questions` VALUES(144, 'Qus', 13, NULL, NULL, NULL);
            //         INSERT INTO `questions` VALUES(145, 'Qus', 13, NULL, NULL, NULL);
            //         ");
            DB::unprepared("
        INSERT INTO `options` VALUES(1, 'TRUE', NULL, NULL, NULL);
        INSERT INTO `options` VALUES(2, 'FALSE', NULL, NULL, NULL);
        INSERT INTO `options` VALUES(3, 'Not Applicable', NULL, NULL, NULL);
        INSERT INTO `options` VALUES(4, 'Rarely', NULL, NULL, NULL);
        INSERT INTO `options` VALUES(5, 'Occasionally', NULL, NULL, NULL);
        INSERT INTO `options` VALUES(6, 'Frequently', NULL, NULL, NULL);
        INSERT INTO `options` VALUES(7, 'Often', NULL, NULL, NULL);
        INSERT INTO `options` VALUES(8, 'Always', NULL, NULL, NULL);
        INSERT INTO `options` VALUES(9, 'Did not apply to me at all', NULL, NULL, NULL);
        INSERT INTO `options` VALUES(10, 'Applied to me to some degree or some of the time', NULL, NULL, NULL);
        INSERT INTO `options` VALUES(11, 'Applied to me to a considerable degree or a good part of time', NULL, NULL, NULL);
        INSERT INTO `options` VALUES(12, 'Applied to me very much or most of the time', NULL, NULL, NULL);
        INSERT INTO `options` VALUES(13, 'Strongly Agree', NULL, NULL, NULL);
        INSERT INTO `options` VALUES(14, 'Agree', NULL, NULL, NULL);
        INSERT INTO `options` VALUES(15, 'Disagree', NULL, NULL, NULL);
        INSERT INTO `options` VALUES(16, 'Strongly Disagree', NULL, NULL, NULL);
        INSERT INTO `options` VALUES(17, 'Not at all', NULL, NULL, NULL);
        INSERT INTO `options` VALUES(18, 'Somewhat', NULL, NULL, NULL);
        INSERT INTO `options` VALUES(19, 'Moderately', NULL, NULL, NULL);
        INSERT INTO `options` VALUES(20, 'Very much', NULL, NULL, NULL);
        INSERT INTO `options` VALUES(21, 'Very Often', NULL, NULL, NULL);
        INSERT INTO `options` VALUES(22, 'Neutral', NULL, NULL, NULL);
        INSERT INTO `options` VALUES(23, 'Yes', NULL, NULL, NULL);
        INSERT INTO `options` VALUES(24, 'No', NULL, NULL, NULL);
        INSERT INTO `options` VALUES(29, 'I am very satisfied with what I am doing at work', NULL, NULL, NULL);
        INSERT INTO `options` VALUES(30, 'My work is not rewarding in some aspects but I stay on for the money', NULL, NULL, NULL);
        INSERT INTO `options` VALUES(31, 'I do not like my work at all', NULL, NULL, NULL);
        INSERT INTO `options` VALUES(32, 'Yes I am a healthy person', NULL, NULL, NULL);
        INSERT INTO `options` VALUES(33, 'I am moderately healthy although I do get sick occasionally', NULL, NULL, NULL);
        INSERT INTO `options` VALUES(34, 'I am not a healthy person as I tend to fall ill quite often', NULL, NULL, NULL);
        INSERT INTO `options` VALUES(35, 'Yes I do help others as often as I can', NULL, NULL, NULL);
        INSERT INTO `options` VALUES(36, 'I help people rarely, once in a while', NULL, NULL, NULL);
        INSERT INTO `options` VALUES(37, 'No, I hardly help others', NULL, NULL, NULL);
        INSERT INTO `options` VALUES(38, 'Sometimes', NULL, NULL, NULL);
        ");
            DB::unprepared(
                "
                INSERT INTO `option_questions` VALUES(1, 60, 9, 0, NULL, NULL, NULL);
                INSERT INTO `option_questions` VALUES(2, 60, 10, 1, NULL, NULL, NULL);
                INSERT INTO `option_questions` VALUES(3, 60, 11, 2, NULL, NULL, NULL);
                INSERT INTO `option_questions` VALUES(4, 60, 12, 3, NULL, NULL, NULL);
                INSERT INTO `option_questions` VALUES(5, 61, 9, 0, NULL, NULL, NULL);
                INSERT INTO `option_questions` VALUES(6, 61, 10, 1, NULL, NULL, NULL);
                INSERT INTO `option_questions` VALUES(7, 61, 11, 2, NULL, NULL, NULL);
                INSERT INTO `option_questions` VALUES(8, 61, 12, 3, NULL, NULL, NULL);
                INSERT INTO `option_questions` VALUES(9, 62, 9, 0, NULL, NULL, NULL);
                INSERT INTO `option_questions` VALUES(10,62, 10, 1, NULL, NULL, NULL);
                INSERT INTO `option_questions` VALUES(11,62, 11, 2, NULL, NULL, NULL);
                INSERT INTO `option_questions` VALUES(12,62, 12, 3, NULL, NULL, NULL);
                INSERT INTO `option_questions` VALUES(13, 63, 9, 0, NULL, NULL, NULL);
                INSERT INTO `option_questions` VALUES(14, 63, 10, 1, NULL, NULL, NULL);
                INSERT INTO `option_questions` VALUES(15, 63, 11, 2, NULL, NULL, NULL);
                INSERT INTO `option_questions` VALUES(16, 63, 12, 3, NULL, NULL, NULL);
                INSERT INTO `option_questions` VALUES(17, 64, 9, 0, NULL, NULL, NULL);
                INSERT INTO `option_questions` VALUES(18, 64, 10, 1, NULL, NULL, NULL);
                INSERT INTO `option_questions` VALUES(19, 64, 11, 2, NULL, NULL, NULL);
                INSERT INTO `option_questions` VALUES(20, 64, 12, 3, NULL, NULL, NULL);
                INSERT INTO `option_questions` VALUES(21, 65, 9, 0, NULL, NULL, NULL);
                INSERT INTO `option_questions` VALUES(22, 65, 10, 1, NULL, NULL, NULL);
                INSERT INTO `option_questions` VALUES(23, 65, 11, 2, NULL, NULL, NULL);
                INSERT INTO `option_questions` VALUES(24, 65, 12, 3, NULL, NULL, NULL);
                INSERT INTO `option_questions` VALUES(25, 66, 9, 0, NULL, NULL, NULL);
                INSERT INTO `option_questions` VALUES(26, 66, 10, 1, NULL, NULL, NULL);
                INSERT INTO `option_questions` VALUES(27, 66, 11, 2, NULL, NULL, NULL);
                INSERT INTO `option_questions` VALUES(28, 66, 12, 3, NULL, NULL, NULL);
                INSERT INTO `option_questions` VALUES(29, 67, 9, 0, NULL, NULL, NULL);
                INSERT INTO `option_questions` VALUES(30, 67, 10, 1, NULL, NULL, NULL);
                INSERT INTO `option_questions` VALUES(31, 67, 11, 2, NULL, NULL, NULL);
                INSERT INTO `option_questions` VALUES(32, 67, 12, 3, NULL, NULL, NULL);
                INSERT INTO `option_questions` VALUES(33, 68, 9, 0, NULL, NULL, NULL);
                INSERT INTO `option_questions` VALUES(34, 68, 10, 1, NULL, NULL, NULL);
                INSERT INTO `option_questions` VALUES(35, 68, 11, 2, NULL, NULL, NULL);
                INSERT INTO `option_questions` VALUES(36, 68, 12, 3, NULL, NULL, NULL);
                INSERT INTO `option_questions` VALUES(37, 69, 9, 0, NULL, NULL, NULL);
                INSERT INTO `option_questions` VALUES(38, 69, 10, 1, NULL, NULL, NULL);
                INSERT INTO `option_questions` VALUES(39, 69, 11, 2, NULL, NULL, NULL);
                INSERT INTO `option_questions` VALUES(40, 69, 12, 3, NULL, NULL, NULL);
                INSERT INTO `option_questions` VALUES(41, 70, 9, 0, NULL, NULL, NULL);
                INSERT INTO `option_questions` VALUES(42, 70, 10, 1, NULL, NULL, NULL);
                INSERT INTO `option_questions` VALUES(43, 70, 11, 2, NULL, NULL, NULL);
                INSERT INTO `option_questions` VALUES(44, 70, 12, 3, NULL, NULL, NULL);
                INSERT INTO `option_questions` VALUES(45, 71, 9, 0, NULL, NULL, NULL);
                INSERT INTO `option_questions` VALUES(46, 71, 10, 1, NULL, NULL, NULL);
                INSERT INTO `option_questions` VALUES(47, 71, 11, 2, NULL, NULL, NULL);
                INSERT INTO `option_questions` VALUES(48, 71, 12, 3, NULL, NULL, NULL);
                INSERT INTO `option_questions` VALUES(49, 72, 9, 0, NULL, NULL, NULL);
                INSERT INTO `option_questions` VALUES(50, 72, 10, 1, NULL, NULL, NULL);
                INSERT INTO `option_questions` VALUES(51, 72, 11, 2, NULL, NULL, NULL);
                INSERT INTO `option_questions` VALUES(52, 72, 12, 3, NULL, NULL, NULL);
                INSERT INTO `option_questions` VALUES(53, 73, 9, 0, NULL, NULL, NULL);
                INSERT INTO `option_questions` VALUES(54, 73, 10, 1, NULL, NULL, NULL);
                INSERT INTO `option_questions` VALUES(55, 73, 11, 2, NULL, NULL, NULL);
                INSERT INTO `option_questions` VALUES(56, 73, 12, 3, NULL, NULL, NULL);
                INSERT INTO `option_questions` VALUES(57, 74, 9, 0, NULL, NULL, NULL);
                INSERT INTO `option_questions` VALUES(58, 74, 10, 1, NULL, NULL, NULL);
                INSERT INTO `option_questions` VALUES(59, 74, 11, 2, NULL, NULL, NULL);
                INSERT INTO `option_questions` VALUES(60, 74, 12, 3, NULL, NULL, NULL);
                INSERT INTO `option_questions` VALUES(61, 75, 9, 0, NULL, NULL, NULL);
                INSERT INTO `option_questions` VALUES(62, 75, 10, 1, NULL, NULL, NULL);
                INSERT INTO `option_questions` VALUES(63, 75, 11, 2, NULL, NULL, NULL);
                INSERT INTO `option_questions` VALUES(64, 75, 12, 3, NULL, NULL, NULL);
                INSERT INTO `option_questions` VALUES(65, 76, 9, 0, NULL, NULL, NULL);
                INSERT INTO `option_questions` VALUES(66, 76, 10, 1, NULL, NULL, NULL);
                INSERT INTO `option_questions` VALUES(67, 76, 11, 2, NULL, NULL, NULL);
                INSERT INTO `option_questions` VALUES(68, 76, 12, 3, NULL, NULL, NULL);
                INSERT INTO `option_questions` VALUES(69, 77, 9, 0, NULL, NULL, NULL);
                INSERT INTO `option_questions` VALUES(70, 77, 10, 1, NULL, NULL, NULL);
                INSERT INTO `option_questions` VALUES(71, 77, 11, 2, NULL, NULL, NULL);
                INSERT INTO `option_questions` VALUES(72, 77, 12, 3, NULL, NULL, NULL);
                INSERT INTO `option_questions` VALUES(73, 78, 9, 0, NULL, NULL, NULL);
                INSERT INTO `option_questions` VALUES(74, 78, 10, 1, NULL, NULL, NULL);
                INSERT INTO `option_questions` VALUES(75, 78, 11, 2, NULL, NULL, NULL);
                INSERT INTO `option_questions` VALUES(76, 78, 12, 3, NULL, NULL, NULL);
                INSERT INTO `option_questions` VALUES(77, 79, 9, 0, NULL, NULL, NULL);
                INSERT INTO `option_questions` VALUES(78, 79, 10, 1, NULL, NULL, NULL);
                INSERT INTO `option_questions` VALUES(79, 79, 11, 2, NULL, NULL, NULL);
                INSERT INTO `option_questions` VALUES(80, 79, 12, 3, NULL, NULL, NULL);
                INSERT INTO `option_questions` VALUES(81, 80, 9, 0, NULL, NULL, NULL);
                INSERT INTO `option_questions` VALUES(82, 80, 10, 1, NULL, NULL, NULL);
                INSERT INTO `option_questions` VALUES(83, 80, 11, 2, NULL, NULL, NULL);
                INSERT INTO `option_questions` VALUES(84, 80, 12, 3, NULL, NULL, NULL);
                INSERT INTO `option_questions` VALUES(85, 81, 17, 1, NULL, NULL, NULL);
                INSERT INTO `option_questions` VALUES(86, 81, 4, 2, NULL, NULL, NULL);
                INSERT INTO `option_questions` VALUES(87, 81, 40, 3, NULL, NULL, NULL);
                INSERT INTO `option_questions` VALUES(88, 81, 7, 4, NULL, NULL, NULL);
                INSERT INTO `option_questions` VALUES(89, 82, 21, 5, NULL, NULL, NULL);
                INSERT INTO `option_questions` VALUES(90, 82, 17, 1, NULL, NULL, NULL);
                INSERT INTO `option_questions` VALUES(91, 82, 4, 2, NULL, NULL, NULL);
                INSERT INTO `option_questions` VALUES(92, 82, 40, 3, NULL, NULL, NULL);
                INSERT INTO `option_questions` VALUES(93, 83, 7, 4, NULL, NULL, NULL);
                INSERT INTO `option_questions` VALUES(94, 83, 21, 5, NULL, NULL, NULL);
                INSERT INTO `option_questions` VALUES(95, 83, 17, 1, NULL, NULL, NULL);
                INSERT INTO `option_questions` VALUES(96, 83, 4, 2, NULL, NULL, NULL);
                INSERT INTO `option_questions` VALUES(97, 84, 40, 3, NULL, NULL, NULL);
                INSERT INTO `option_questions` VALUES(98, 84, 7, 4, NULL, NULL, NULL);
                INSERT INTO `option_questions` VALUES(99, 84, 21, 5, NULL, NULL, NULL);
                INSERT INTO `option_questions` VALUES(100,84, 17, 1, NULL, NULL, NULL);
                INSERT INTO `option_questions` VALUES(101, 85, 4, 2, NULL, NULL, NULL);
                INSERT INTO `option_questions` VALUES(102, 85, 40, 3, NULL, NULL, NULL);
                INSERT INTO `option_questions` VALUES(103, 85, 7, 4, NULL, NULL, NULL);
                INSERT INTO `option_questions` VALUES(104, 85, 21, 5, NULL, NULL, NULL);
                INSERT INTO `option_questions` VALUES(105, 86, 17, 1, NULL, NULL, NULL);
                INSERT INTO `option_questions` VALUES(106, 86, 4, 2, NULL, NULL, NULL);
                INSERT INTO `option_questions` VALUES(107, 86, 40, 3, NULL, NULL, NULL);
                INSERT INTO `option_questions` VALUES(108, 86, 7, 4, NULL, NULL, NULL);
                INSERT INTO `option_questions` VALUES(109, 86, 21, 5, NULL, NULL, NULL);
                INSERT INTO `option_questions` VALUES(187, 104, 13, 4, NULL, NULL, NULL);
                INSERT INTO `option_questions` VALUES(188, 104, 14, 3, NULL, NULL, NULL);
                INSERT INTO `option_questions` VALUES(189, 104, 15, 2, NULL, NULL, NULL);
                INSERT INTO `option_questions` VALUES(190, 104, 16, 1, NULL, NULL, NULL);
                INSERT INTO `option_questions` VALUES(191, 105, 13, 4, NULL, NULL, NULL);
                INSERT INTO `option_questions` VALUES(192, 105, 14, 3, NULL, NULL, NULL);
                INSERT INTO `option_questions` VALUES(193, 105, 15, 2, NULL, NULL, NULL);
                INSERT INTO `option_questions` VALUES(194, 105, 16, 1, NULL, NULL, NULL);
                INSERT INTO `option_questions` VALUES(195, 106, 13, 4, NULL, NULL, NULL);
                INSERT INTO `option_questions` VALUES(196, 106, 14, 3, NULL, NULL, NULL);
                INSERT INTO `option_questions` VALUES(197, 106, 15, 2, NULL, NULL, NULL);
                INSERT INTO `option_questions` VALUES(198, 106, 16, 1, NULL, NULL, NULL);
                INSERT INTO `option_questions` VALUES(199, 107, 13, 4, NULL, NULL, NULL);
                INSERT INTO `option_questions` VALUES(200, 107, 14, 3, NULL, NULL, NULL);
                INSERT INTO `option_questions` VALUES(201, 107, 15, 2, NULL, NULL, NULL);
                INSERT INTO `option_questions` VALUES(202, 107, 16, 1, NULL, NULL, NULL);
                INSERT INTO `option_questions` VALUES(203, 108, 13, 4, NULL, NULL, NULL);
                INSERT INTO `option_questions` VALUES(204, 108, 14, 3, NULL, NULL, NULL);
                INSERT INTO `option_questions` VALUES(205, 108, 15, 2, NULL, NULL, NULL);
                INSERT INTO `option_questions` VALUES(206, 108, 16, 1, NULL, NULL, NULL);
                INSERT INTO `option_questions` VALUES(207, 109, 13, 4, NULL, NULL, NULL);
                INSERT INTO `option_questions` VALUES(208, 109, 14, 3, NULL, NULL, NULL);
                INSERT INTO `option_questions` VALUES(209, 109, 15, 2, NULL, NULL, NULL);
                INSERT INTO `option_questions` VALUES(210, 109, 16, 1, NULL, NULL, NULL);
                INSERT INTO `option_questions` VALUES(211, 110, 13, 4, NULL, NULL, NULL);
                INSERT INTO `option_questions` VALUES(212, 110, 14, 3, NULL, NULL, NULL);
                INSERT INTO `option_questions` VALUES(213, 110, 15, 2, NULL, NULL, NULL);
                INSERT INTO `option_questions` VALUES(214, 110, 16, 1, NULL, NULL, NULL);
                INSERT INTO `option_questions` VALUES(215, 111, 13, 4, NULL, NULL, NULL);
                INSERT INTO `option_questions` VALUES(216, 111, 14, 3, NULL, NULL, NULL);
                INSERT INTO `option_questions` VALUES(217, 111, 15, 2, NULL, NULL, NULL);
                INSERT INTO `option_questions` VALUES(218, 111, 16, 1, NULL, NULL, NULL);
                INSERT INTO `option_questions` VALUES(219, 112, 13, 4, NULL, NULL, NULL);
                INSERT INTO `option_questions` VALUES(220, 112, 14, 3, NULL, NULL, NULL);
                INSERT INTO `option_questions` VALUES(221, 112, 15, 2, NULL, NULL, NULL);
                INSERT INTO `option_questions` VALUES(222, 112, 16, 1, NULL, NULL, NULL);
                INSERT INTO `option_questions` VALUES(223, 113, 13, 4, NULL, NULL, NULL);
                INSERT INTO `option_questions` VALUES(224, 113, 14, 3, NULL, NULL, NULL);
                INSERT INTO `option_questions` VALUES(225, 113, 15, 2, NULL, NULL, NULL);
                INSERT INTO `option_questions` VALUES(226, 113, 16, 1, NULL, NULL, NULL);
                INSERT INTO `option_questions` VALUES(227, 114, 17, 1, NULL, NULL, NULL);
                INSERT INTO `option_questions` VALUES(228, 114, 18, 2, NULL, NULL, NULL);
                INSERT INTO `option_questions` VALUES(229, 114, 19, 3, NULL, NULL, NULL);
                INSERT INTO `option_questions` VALUES(230, 114, 20, 4, NULL, NULL, NULL);
                INSERT INTO `option_questions` VALUES(231, 115, 17, 1, NULL, NULL, NULL);
                INSERT INTO `option_questions` VALUES(232, 115, 18, 2, NULL, NULL, NULL);
                INSERT INTO `option_questions` VALUES(233, 115, 19, 3, NULL, NULL, NULL);
                INSERT INTO `option_questions` VALUES(234, 115, 20, 4, NULL, NULL, NULL);
                INSERT INTO `option_questions` VALUES(235, 116, 17, 1, NULL, NULL, NULL);
                INSERT INTO `option_questions` VALUES(236, 116, 18, 2, NULL, NULL, NULL);
                INSERT INTO `option_questions` VALUES(237, 116, 19, 3, NULL, NULL, NULL);
                INSERT INTO `option_questions` VALUES(238, 116, 20, 4, NULL, NULL, NULL);
                INSERT INTO `option_questions` VALUES(239, 117, 17, 1, NULL, NULL, NULL);
                INSERT INTO `option_questions` VALUES(240, 117, 18, 2, NULL, NULL, NULL);
                INSERT INTO `option_questions` VALUES(241, 117, 19, 3, NULL, NULL, NULL);
                INSERT INTO `option_questions` VALUES(242, 117, 20, 4, NULL, NULL, NULL);
                INSERT INTO `option_questions` VALUES(243, 118, 17, 1, NULL, NULL, NULL);
                INSERT INTO `option_questions` VALUES(244, 118, 18, 2, NULL, NULL, NULL);
                INSERT INTO `option_questions` VALUES(245, 118, 19, 3, NULL, NULL, NULL);
                INSERT INTO `option_questions` VALUES(246, 118, 20, 4, NULL, NULL, NULL);
                INSERT INTO `option_questions` VALUES(247, 119, 17, 1, NULL, NULL, NULL);
                INSERT INTO `option_questions` VALUES(248, 119, 18, 2, NULL, NULL, NULL);
                INSERT INTO `option_questions` VALUES(249, 119, 19, 3, NULL, NULL, NULL);
                INSERT INTO `option_questions` VALUES(250, 119, 20, 4, NULL, NULL, NULL);
                INSERT INTO `option_questions` VALUES(251, 120, 17, 1, NULL, NULL, NULL);
                INSERT INTO `option_questions` VALUES(252, 120, 18, 2, NULL, NULL, NULL);
                INSERT INTO `option_questions` VALUES(253, 120, 19, 3, NULL, NULL, NULL);
                INSERT INTO `option_questions` VALUES(254, 120, 20, 4, NULL, NULL, NULL);
                INSERT INTO `option_questions` VALUES(255, 121, 17, 1, NULL, NULL, NULL);
                INSERT INTO `option_questions` VALUES(256, 121, 18, 2, NULL, NULL, NULL);
                INSERT INTO `option_questions` VALUES(257, 121, 19, 3, NULL, NULL, NULL);
                INSERT INTO `option_questions` VALUES(258, 121, 20, 4, NULL, NULL, NULL);
                INSERT INTO `option_questions` VALUES(259, 122, 17, 1, NULL, NULL, NULL);
                INSERT INTO `option_questions` VALUES(260, 122, 18, 2, NULL, NULL, NULL);
                INSERT INTO `option_questions` VALUES(261, 122, 19, 3, NULL, NULL, NULL);
                INSERT INTO `option_questions` VALUES(262, 122, 20, 4, NULL, NULL, NULL);
                INSERT INTO `option_questions` VALUES(263, 123, 17, 1, NULL, NULL, NULL);
                INSERT INTO `option_questions` VALUES(264, 123, 18, 2, NULL, NULL, NULL);
                INSERT INTO `option_questions` VALUES(265, 123, 19, 3, NULL, NULL, NULL);
                INSERT INTO `option_questions` VALUES(266, 123, 20, 4, NULL, NULL, NULL);
                INSERT INTO `option_questions` VALUES(267, 124, 17, 1, NULL, NULL, NULL);
                INSERT INTO `option_questions` VALUES(268, 124, 18, 2, NULL, NULL, NULL);
                INSERT INTO `option_questions` VALUES(269, 124, 19, 3, NULL, NULL, NULL);
                INSERT INTO `option_questions` VALUES(270, 124, 20, 4, NULL, NULL, NULL);
                INSERT INTO `option_questions` VALUES(271, 125, 17, 1, NULL, NULL, NULL);
                INSERT INTO `option_questions` VALUES(272, 125, 18, 2, NULL, NULL, NULL);
                INSERT INTO `option_questions` VALUES(273, 125, 19, 3, NULL, NULL, NULL);
                INSERT INTO `option_questions` VALUES(274, 125, 20, 4, NULL, NULL, NULL);
                INSERT INTO `option_questions` VALUES(275, 126, 16, 1, NULL, NULL, NULL);
                INSERT INTO `option_questions` VALUES(276, 126, 15, 2, NULL, NULL, NULL);
                INSERT INTO `option_questions` VALUES(277, 126, 22, 3, NULL, NULL, NULL);
                INSERT INTO `option_questions` VALUES(278, 126, 14, 4, NULL, NULL, NULL);
                INSERT INTO `option_questions` VALUES(279, 126, 13, 5, NULL, NULL, NULL);
                INSERT INTO `option_questions` VALUES(280, 127, 16, 1, NULL, NULL, NULL);
                INSERT INTO `option_questions` VALUES(281, 127, 15, 2, NULL, NULL, NULL);
                INSERT INTO `option_questions` VALUES(282, 127, 22, 3, NULL, NULL, NULL);
                INSERT INTO `option_questions` VALUES(283, 127, 14, 4, NULL, NULL, NULL);
                INSERT INTO `option_questions` VALUES(284, 127, 13, 5, NULL, NULL, NULL);
                INSERT INTO `option_questions` VALUES(285, 128, 16, 1, NULL, NULL, NULL);
                INSERT INTO `option_questions` VALUES(286, 128, 15, 2, NULL, NULL, NULL);
                INSERT INTO `option_questions` VALUES(287, 128, 22, 3, NULL, NULL, NULL);
                INSERT INTO `option_questions` VALUES(288, 128, 14, 4, NULL, NULL, NULL);
                INSERT INTO `option_questions` VALUES(289, 128, 13, 5, NULL, NULL, NULL);
                INSERT INTO `option_questions` VALUES(290, 129, 16, 1, NULL, NULL, NULL);
                INSERT INTO `option_questions` VALUES(291, 129, 15, 2, NULL, NULL, NULL);
                INSERT INTO `option_questions` VALUES(292, 129, 22, 3, NULL, NULL, NULL);
                INSERT INTO `option_questions` VALUES(293, 129, 14, 4, NULL, NULL, NULL);
                INSERT INTO `option_questions` VALUES(294, 129, 13, 5, NULL, NULL, NULL);
                INSERT INTO `option_questions` VALUES(295, 130, 16, 1, NULL, NULL, NULL);
                INSERT INTO `option_questions` VALUES(296, 130, 15, 2, NULL, NULL, NULL);
                INSERT INTO `option_questions` VALUES(297, 130, 22, 3, NULL, NULL, NULL);
                INSERT INTO `option_questions` VALUES(298, 130, 14, 4, NULL, NULL, NULL);
                INSERT INTO `option_questions` VALUES(299, 130, 13, 5, NULL, NULL, NULL);
                INSERT INTO `option_questions` VALUES(300, 131, 16, 1, NULL, NULL, NULL);
                INSERT INTO `option_questions` VALUES(301, 131, 15, 2, NULL, NULL, NULL);
                INSERT INTO `option_questions` VALUES(302, 131, 22, 3, NULL, NULL, NULL);
                INSERT INTO `option_questions` VALUES(303, 131, 14, 4, NULL, NULL, NULL);
                INSERT INTO `option_questions` VALUES(304, 131, 13, 5, NULL, NULL, NULL);
                INSERT INTO `option_questions` VALUES(305, 132, 16, 1, NULL, NULL, NULL);
                INSERT INTO `option_questions` VALUES(306, 132, 15, 2, NULL, NULL, NULL);
                INSERT INTO `option_questions` VALUES(307, 132, 22, 3, NULL, NULL, NULL);
                INSERT INTO `option_questions` VALUES(308, 132, 14, 4, NULL, NULL, NULL);
                INSERT INTO `option_questions` VALUES(309, 132, 13, 5, NULL, NULL, NULL);
                INSERT INTO `option_questions` VALUES(310, 133, 16, 1, NULL, NULL, NULL);
                INSERT INTO `option_questions` VALUES(311, 133, 15, 2, NULL, NULL, NULL);
                INSERT INTO `option_questions` VALUES(312, 133, 22, 3, NULL, NULL, NULL);
                INSERT INTO `option_questions` VALUES(313, 133, 14, 4, NULL, NULL, NULL);
                INSERT INTO `option_questions` VALUES(314, 133, 13, 5, NULL, NULL, NULL);
                INSERT INTO `option_questions` VALUES(315, 134, 16, 1, NULL, NULL, NULL);
                INSERT INTO `option_questions` VALUES(316, 134, 15, 2, NULL, NULL, NULL);
                INSERT INTO `option_questions` VALUES(317, 134, 22, 3, NULL, NULL, NULL);
                INSERT INTO `option_questions` VALUES(318, 134, 14, 4, NULL, NULL, NULL);
                INSERT INTO `option_questions` VALUES(319, 134, 13, 5, NULL, NULL, NULL);
                INSERT INTO `option_questions` VALUES(320, 135, 16, 1, NULL, NULL, NULL);
                INSERT INTO `option_questions` VALUES(321, 135, 15, 2, NULL, NULL, NULL);
                INSERT INTO `option_questions` VALUES(322, 135, 22, 3, NULL, NULL, NULL);
                INSERT INTO `option_questions` VALUES(323, 135, 14, 4, NULL, NULL, NULL);
                INSERT INTO `option_questions` VALUES(324, 135, 13, 5, NULL, NULL, NULL);
                INSERT INTO `option_questions` VALUES(325, 136, 16, 1, NULL, NULL, NULL);
                INSERT INTO `option_questions` VALUES(326, 136, 15, 2, NULL, NULL, NULL);
                INSERT INTO `option_questions` VALUES(327, 136, 22, 3, NULL, NULL, NULL);
                INSERT INTO `option_questions` VALUES(328, 136, 14, 4, NULL, NULL, NULL);
                INSERT INTO `option_questions` VALUES(329, 136, 13, 5, NULL, NULL, NULL);
                INSERT INTO `option_questions` VALUES(330, 137, 16, 1, NULL, NULL, NULL);
                INSERT INTO `option_questions` VALUES(331, 137, 15, 2, NULL, NULL, NULL);
                INSERT INTO `option_questions` VALUES(332, 137, 22, 3, NULL, NULL, NULL);
                INSERT INTO `option_questions` VALUES(333, 137, 14, 4, NULL, NULL, NULL);
                INSERT INTO `option_questions` VALUES(334, 137, 13, 5, NULL, NULL, NULL);
                INSERT INTO `option_questions` VALUES(335, 138, 16, 1, NULL, NULL, NULL);
                INSERT INTO `option_questions` VALUES(336, 138, 15, 2, NULL, NULL, NULL);
                INSERT INTO `option_questions` VALUES(337, 138, 22, 3, NULL, NULL, NULL);
                INSERT INTO `option_questions` VALUES(338, 138, 14, 4, NULL, NULL, NULL);
                INSERT INTO `option_questions` VALUES(339, 138, 13, 5, NULL, NULL, NULL);
                INSERT INTO `option_questions` VALUES(340, 139, 16, 1, NULL, NULL, NULL);
                INSERT INTO `option_questions` VALUES(341, 139, 15, 2, NULL, NULL, NULL);
                INSERT INTO `option_questions` VALUES(342, 139, 22, 3, NULL, NULL, NULL);
                INSERT INTO `option_questions` VALUES(343, 139, 14, 4, NULL, NULL, NULL);
                INSERT INTO `option_questions` VALUES(344, 139, 13, 5, NULL, NULL, NULL);
                INSERT INTO `option_questions` VALUES(345, 140, 16, 1, NULL, NULL, NULL);
                INSERT INTO `option_questions` VALUES(346, 140, 15, 2, NULL, NULL, NULL);
                INSERT INTO `option_questions` VALUES(347, 140, 22, 3, NULL, NULL, NULL);
                INSERT INTO `option_questions` VALUES(348, 140, 14, 4, NULL, NULL, NULL);
                INSERT INTO `option_questions` VALUES(349, 140, 13, 5, NULL, NULL, NULL);
                INSERT INTO `option_questions` VALUES(350, 141, 16, 1, NULL, NULL, NULL);
                INSERT INTO `option_questions` VALUES(351, 141, 15, 2, NULL, NULL, NULL);
                INSERT INTO `option_questions` VALUES(352, 141, 22, 3, NULL, NULL, NULL);
                INSERT INTO `option_questions` VALUES(353, 141, 14, 4, NULL, NULL, NULL);
                INSERT INTO `option_questions` VALUES(354, 141, 13, 5, NULL, NULL, NULL);
                INSERT INTO `option_questions` VALUES(355, 142, 23, 1, NULL, NULL, NULL);
                INSERT INTO `option_questions` VALUES(356, 142, 24, 0, NULL, NULL, NULL);
                INSERT INTO `option_questions` VALUES(357, 143, 23, 1, NULL, NULL, NULL);
                INSERT INTO `option_questions` VALUES(358, 143, 24, 0, NULL, NULL, NULL);
                INSERT INTO `option_questions` VALUES(359, 144, 23, 1, NULL, NULL, NULL);
                INSERT INTO `option_questions` VALUES(360, 144, 24, 0, NULL, NULL, NULL);
                INSERT INTO `option_questions` VALUES(361, 145, 23, 1, NULL, NULL, NULL);
                INSERT INTO `option_questions` VALUES(362, 145, 24, 0, NULL, NULL, NULL);

            INSERT INTO `option_questions` VALUES(363, 1, 1, 1, NULL, NULL, NULL);
            INSERT INTO `option_questions` VALUES(364, 1, 2, 0, NULL, NULL, NULL);
            INSERT INTO `option_questions` VALUES(365, 2, 1, 1, NULL, NULL, NULL);
            INSERT INTO `option_questions` VALUES(366, 2, 2, 0, NULL, NULL, NULL);
            INSERT INTO `option_questions` VALUES(367, 3, 1, 1, NULL, NULL, NULL);
            INSERT INTO `option_questions` VALUES(368, 3, 2, 0, NULL, NULL, NULL);
            INSERT INTO `option_questions` VALUES(369, 4, 1, 1, NULL, NULL, NULL);
            INSERT INTO `option_questions` VALUES(370, 4, 2, 0, NULL, NULL, NULL);
            INSERT INTO `option_questions` VALUES(371, 5, 1, 1, NULL, NULL, NULL);
            INSERT INTO `option_questions` VALUES(372, 5, 2, 0, NULL, NULL, NULL);
            INSERT INTO `option_questions` VALUES(373, 6, 1, 1, NULL, NULL, NULL);
            INSERT INTO `option_questions` VALUES(374, 6, 2, 0, NULL, NULL, NULL);
            INSERT INTO `option_questions` VALUES(375, 7, 1, 1, NULL, NULL, NULL);
            INSERT INTO `option_questions` VALUES(376, 7, 2, 0, NULL, NULL, NULL);
            INSERT INTO `option_questions` VALUES(377, 8, 1, 1, NULL, NULL, NULL);
            INSERT INTO `option_questions` VALUES(378, 8, 2, 0, NULL, NULL, NULL);
            INSERT INTO `option_questions` VALUES(379, 9, 1, 1, NULL, NULL, NULL);
            INSERT INTO `option_questions` VALUES(380, 9, 2, 0, NULL, NULL, NULL);
            INSERT INTO `option_questions` VALUES(381, 10, 1, 1, NULL, NULL, NULL);
            INSERT INTO `option_questions` VALUES(382, 10, 2, 0, NULL, NULL, NULL);
            INSERT INTO `option_questions` VALUES(383, 11, 1, 1, NULL, NULL, NULL);
            INSERT INTO `option_questions` VALUES(384, 11, 2, 0, NULL, NULL, NULL);
            INSERT INTO `option_questions` VALUES(385, 12, 1, 1, NULL, NULL, NULL);
            INSERT INTO `option_questions` VALUES(386, 12, 2, 0, NULL, NULL, NULL);
            INSERT INTO `option_questions` VALUES(387, 13, 1, 1, NULL, NULL, NULL);
            INSERT INTO `option_questions` VALUES(388, 13, 2, 0, NULL, NULL, NULL);
            INSERT INTO `option_questions` VALUES(389, 14, 1, 1, NULL, NULL, NULL);
            INSERT INTO `option_questions` VALUES(390, 14, 2, 0, NULL, NULL, NULL);
            INSERT INTO `option_questions` VALUES(391, 15, 1, 1, NULL, NULL, NULL);
            INSERT INTO `option_questions` VALUES(392, 15, 2, 0, NULL, NULL, NULL);
            INSERT INTO `option_questions` VALUES(393, 16, 1, 1, NULL, NULL, NULL);
            INSERT INTO `option_questions` VALUES(394, 16, 2, 0, NULL, NULL, NULL);
            INSERT INTO `option_questions` VALUES(395, 17, 1, 1, NULL, NULL, NULL);
            INSERT INTO `option_questions` VALUES(396, 17, 2, 0, NULL, NULL, NULL);
            INSERT INTO `option_questions` VALUES(397, 18, 1, 1, NULL, NULL, NULL);
            INSERT INTO `option_questions` VALUES(398, 18, 2, 0, NULL, NULL, NULL);
            INSERT INTO `option_questions` VALUES(399, 19, 1, 1, NULL, NULL, NULL);
            INSERT INTO `option_questions` VALUES(400, 19, 2, 0, NULL, NULL, NULL);
            INSERT INTO `option_questions` VALUES(401, 20, 1, 1, NULL, NULL, NULL);
            INSERT INTO `option_questions` VALUES(402, 20, 2, 0, NULL, NULL, NULL);
            INSERT INTO `option_questions` VALUES(403, 21, 1, 1, NULL, NULL, NULL);
            INSERT INTO `option_questions` VALUES(404, 21, 2, 0, NULL, NULL, NULL);
            INSERT INTO `option_questions` VALUES(405, 22, 1, 1, NULL, NULL, NULL);
            INSERT INTO `option_questions` VALUES(406, 22, 2, 0, NULL, NULL, NULL);
            INSERT INTO `option_questions` VALUES(407, 23, 1, 1, NULL, NULL, NULL);
            INSERT INTO `option_questions` VALUES(408, 23, 2, 0, NULL, NULL, NULL);
            INSERT INTO `option_questions` VALUES(409, 24, 1, 1, NULL, NULL, NULL);
            INSERT INTO `option_questions` VALUES(410, 24, 2, 0, NULL, NULL, NULL);
            INSERT INTO `option_questions` VALUES(411, 25, 1, 1, NULL, NULL, NULL);
            INSERT INTO `option_questions` VALUES(412, 25, 2, 0, NULL, NULL, NULL);
            INSERT INTO `option_questions` VALUES(413, 26, 1, 1, NULL, NULL, NULL);
            INSERT INTO `option_questions` VALUES(414, 26, 2, 0, NULL, NULL, NULL);
            INSERT INTO `option_questions` VALUES(415, 27, 1, 1, NULL, NULL, NULL);
            INSERT INTO `option_questions` VALUES(416, 27, 2, 0, NULL, NULL, NULL);
            INSERT INTO `option_questions` VALUES(417, 28, 1, 1, NULL, NULL, NULL);
            INSERT INTO `option_questions` VALUES(418, 28, 2, 0, NULL, NULL, NULL);
            INSERT INTO `option_questions` VALUES(419, 29, 1, 1, NULL, NULL, NULL);
            INSERT INTO `option_questions` VALUES(420, 29, 2, 0, NULL, NULL, NULL);
            INSERT INTO `option_questions` VALUES(421, 30, 1, 1, NULL, NULL, NULL);
            INSERT INTO `option_questions` VALUES(422, 30, 2, 0, NULL, NULL, NULL);
            INSERT INTO `option_questions` VALUES(423, 31, 1, 1, NULL, NULL, NULL);
            INSERT INTO `option_questions` VALUES(424, 31, 2, 0, NULL, NULL, NULL);
            INSERT INTO `option_questions` VALUES(425, 32, 1, 1, NULL, NULL, NULL);
            INSERT INTO `option_questions` VALUES(426, 32, 2, 0, NULL, NULL, NULL);
            INSERT INTO `option_questions` VALUES(427, 33, 1, 1, NULL, NULL, NULL);
            INSERT INTO `option_questions` VALUES(428, 33, 2, 0, NULL, NULL, NULL);
            INSERT INTO `option_questions` VALUES(429, 34, 1, 1, NULL, NULL, NULL);
            INSERT INTO `option_questions` VALUES(430, 34, 2, 0, NULL, NULL, NULL);
            INSERT INTO `option_questions` VALUES(431, 35, 1, 1, NULL, NULL, NULL);
            INSERT INTO `option_questions` VALUES(432, 35, 2, 0, NULL, NULL, NULL);
            INSERT INTO `option_questions` VALUES(433, 36, 1, 1, NULL, NULL, NULL);
            INSERT INTO `option_questions` VALUES(434, 36, 2, 0, NULL, NULL, NULL);
            INSERT INTO `option_questions` VALUES(435, 37, 1, 1, NULL, NULL, NULL);
            INSERT INTO `option_questions` VALUES(436, 37, 2, 0, NULL, NULL, NULL);
            INSERT INTO `option_questions` VALUES(437, 38, 1, 1, NULL, NULL, NULL);
            INSERT INTO `option_questions` VALUES(438, 38, 2, 0, NULL, NULL, NULL);
            INSERT INTO `option_questions` VALUES(439, 39, 1, 1, NULL, NULL, NULL);
            INSERT INTO `option_questions` VALUES(440, 39, 2, 0, NULL, NULL, NULL);
            INSERT INTO `option_questions` VALUES(441, 40, 1, 1, NULL, NULL, NULL);
            INSERT INTO `option_questions` VALUES(442, 40, 2, 0, NULL, NULL, NULL);
            INSERT INTO `option_questions` VALUES(443, 41, 1, 1, NULL, NULL, NULL);
            INSERT INTO `option_questions` VALUES(444, 41, 2, 0, NULL, NULL, NULL);
            INSERT INTO `option_questions` VALUES(445, 42, 1, 1, NULL, NULL, NULL);
            INSERT INTO `option_questions` VALUES(446, 42, 2, 0, NULL, NULL, NULL);
            INSERT INTO `option_questions` VALUES(447, 43, 1, 1, NULL, NULL, NULL);
            INSERT INTO `option_questions` VALUES(448, 43, 2, 0, NULL, NULL, NULL);
            INSERT INTO `option_questions` VALUES(449, 44, 1, 1, NULL, NULL, NULL);
            INSERT INTO `option_questions` VALUES(450, 44, 2, 0, NULL, NULL, NULL);
            INSERT INTO `option_questions` VALUES(451, 45, 1, 1, NULL, NULL, NULL);
            INSERT INTO `option_questions` VALUES(452, 45, 2, 0, NULL, NULL, NULL);
            INSERT INTO `option_questions` VALUES(453, 46, 1, 1, NULL, NULL, NULL);
            INSERT INTO `option_questions` VALUES(454, 46, 2, 0, NULL, NULL, NULL);
            INSERT INTO `option_questions` VALUES(455, 47, 1, 1, NULL, NULL, NULL);
            INSERT INTO `option_questions` VALUES(456, 47, 2, 0, NULL, NULL, NULL);
            INSERT INTO `option_questions` VALUES(457, 48, 1, 1, NULL, NULL, NULL);
            INSERT INTO `option_questions` VALUES(458, 48, 2, 0, NULL, NULL, NULL);
            INSERT INTO `option_questions` VALUES(459, 49, 1, 1, NULL, NULL, NULL);
            INSERT INTO `option_questions` VALUES(460, 49, 2, 0, NULL, NULL, NULL);
            INSERT INTO `option_questions` VALUES(461, 50, 1, 1, NULL, NULL, NULL);
            INSERT INTO `option_questions` VALUES(462, 50, 2, 0, NULL, NULL, NULL);
            INSERT INTO `option_questions` VALUES(463, 51, 1, 1, NULL, NULL, NULL);
            INSERT INTO `option_questions` VALUES(464, 51, 2, 0, NULL, NULL, NULL);
            INSERT INTO `option_questions` VALUES(465, 52, 1, 1, NULL, NULL, NULL);
            INSERT INTO `option_questions` VALUES(466, 52, 2, 0, NULL, NULL, NULL);
            INSERT INTO `option_questions` VALUES(467, 53, 1, 1, NULL, NULL, NULL);
            INSERT INTO `option_questions` VALUES(468, 53, 2, 0, NULL, NULL, NULL);
            INSERT INTO `option_questions` VALUES(469, 54, 1, 1, NULL, NULL, NULL);
            INSERT INTO `option_questions` VALUES(470, 54, 2, 0, NULL, NULL, NULL);
            INSERT INTO `option_questions` VALUES(471, 55, 1, 1, NULL, NULL, NULL);
            INSERT INTO `option_questions` VALUES(472, 55, 2, 0, NULL, NULL, NULL);
            INSERT INTO `option_questions` VALUES(473, 56, 1, 1, NULL, NULL, NULL);
            INSERT INTO `option_questions` VALUES(474, 56, 2, 0, NULL, NULL, NULL);
            INSERT INTO `option_questions` VALUES(475, 57, 1, 1, NULL, NULL, NULL);
            INSERT INTO `option_questions` VALUES(476, 57, 2, 0, NULL, NULL, NULL);
            INSERT INTO `option_questions` VALUES(477, 58, 1, 1, NULL, NULL, NULL);
            INSERT INTO `option_questions` VALUES(478, 58, 2, 0, NULL, NULL, NULL);
            INSERT INTO `option_questions` VALUES(479, 59, 1, 1, NULL, NULL, NULL);
            INSERT INTO `option_questions` VALUES(480, 59, 2, 0, NULL, NULL, NULL);
        "
            );
        });
    }
}
